# Generated by Django 4.2.30 on 2026-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_status',
            field=models.CharField(choices=[('pre_arrival', '入境前準備中'), ('arrived', '已抵臺就學中')], default='applied', max_length=20, verbose_name='入學狀態'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='identity_type',
            field=models.CharField(choices=[('overseas_chinese_student', '僑生（海外華裔）'), ('foreign_student', '外籍生（一般外國學生）')], max_length=30, verbose_name='身份別'),
        ),
    ]
