# Generated by Django 6.0.4 on 2026-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentprofile_admission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_status',
            field=models.CharField(choices=[('pre_arrival', '入臺前準備'), ('arrived', '抵臺後')], default='pre_arrival', max_length=20, verbose_name='入學狀態'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='identity_type',
            field=models.CharField(choices=[('overseas_chinese', '僑生（海外華裔）'), ('foreign_student', '外籍生（一般外國學生）'), ('hong_kong_macau', '港澳生')], max_length=30, verbose_name='身份別'),
        ),
    ]
