# Generated by Django 4.2.30 on 2026-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_admission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='identity_type',
            field=models.CharField(choices=[('overseas_chinese', '僑生'), ('foreign_student', '外籍生'), ('hong_kong_macau', '港澳生')], max_length=30, verbose_name='身份別'),
        ),
    ]
