# Generated by Django 6.0.4 on 2026-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentprofile_identity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(choices=[('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Japan', '日本'), ('Korea', '韓國'), ('Hong Kong', '香港'), ('Macao', '澳門'), ('Other', '其他')], max_length=50, verbose_name='國籍'),
        ),
    ]
