# Generated by Django 6.0.4 on 2026-05-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_nationality'),
        ('users', '0005_alter_studentprofile_university'),
    ]

    operations = [
    ]
