# Generated by Django 4.2.30 on 2026-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('East Asia', '東亞'), ('Southeast Asia', '東南亞'), ('South Asia', '南亞'), ('Middle East', '中東'), ('Europe', '歐洲'), ('North America', '北美洲'), ('Latin America', '中南美洲'), ('Africa', '非洲'), ('Oceania', '大洋洲')], max_length=50, null=True, verbose_name='所屬地區'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(choices=[('Japan', '日本'), ('Korea', '韓國'), ('Macau', '澳門'), ('Hong Kong', '香港'), ('Mongolia', '蒙古'), ('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Singapore', '新加坡'), ('India', '印度'), ('Pakistan', '巴基斯坦'), ('Bangladesh', '孟加拉'), ('Saudi Arabia', '沙烏地阿拉伯'), ('UAE', '阿拉伯聯合大公國'), ('Turkey', '土耳其'), ('UK', '英國'), ('France', '法國'), ('Germany', '德國'), ('Italy', '義大利'), ('Spain', '西班牙'), ('USA', '美國'), ('Canada', '加拿大'), ('Brazil', '巴西'), ('Mexico', '墨西哥'), ('Argentina', '阿根廷'), ('South Africa', '南非'), ('Egypt', '埃及'), ('Nigeria', '奈及利亞'), ('Australia', '澳洲'), ('New Zealand', '紐西蘭'), ('Other', '其他')], max_length=50, verbose_name='國籍'),
        ),
    ]
