# Generated by Django 6.0.4 on 2026-05-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260515_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='has_indo_prep',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否上印輔班'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_taiwan_id',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否擁有台灣身份證'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_deferred',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否延遲入學'),
        ),
    ]
