# Generated by Django 6.0.4 on 2026-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_region_and_more'),
        ('users', '0007_studentprofile_has_indo_prep_and_more'),
    ]

    operations = [
    ]
