# Generated by Django 4.2.30 on 2026-06-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20260518_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='has_indo_prep',
        ),
    ]
