# Generated by Django 6.0.4 on 2026-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_studentprofile_has_indo_prep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('NTU', '國立臺灣大學（NTU）'), ('NCCU', '國立政治大學（NCCU）'), ('NTHU', '國立清華大學（NTHU）'), ('NYCU', '國立陽明交通大學（NYCU）'), ('NCKU', '國立成功大學（NCKU）'), ('NCHU', '國立中興大學（NCHU）'), ('NCU', '國立中央大學（NCU）'), ('NSYSU', '國立中山大學（NSYSU）'), ('NTNU', '國立臺灣師範大學（NTNU）'), ('NTPU', '國立臺北大學（NTPU）'), ('NUTN', '國立臺南大學（NUTN）'), ('NCYU', '國立嘉義大學（NCYU）'), ('NDHU', '國立東華大學（NDHU）'), ('NCNU', '國立暨南國際大學（NCNU）'), ('NIU', '國立宜蘭大學（NIU）'), ('NUU', '國立聯合大學（NUU）'), ('NTTU', '國立臺東大學（NTTU）'), ('NQU', '國立金門大學（NQU）'), ('NPU', '國立澎湖科技大學（NPU）'), ('NTUST', '國立臺灣科技大學（NTUST）'), ('NTUT', '國立臺北科技大學（NTUT）'), ('NKUST', '國立高雄科技大學（NKUST）'), ('YunTech', '國立雲林科技大學（YunTech）'), ('NPUST', '國立屏東科技大學（NPUST）'), ('NTCUST', '國立臺中科技大學（NTCUST）'), ('NFU', '國立虎尾科技大學（NFU）'), ('NKUHT', '國立高雄餐旅大學（NKUHT）'), ('NKNU', '國立高雄師範大學（NKNU）'), ('NCUE', '國立彰化師範大學（NCUE）'), ('NTUE', '國立臺北教育大學（NTUE）'), ('NTCU', '國立臺中教育大學（NTCU）'), ('NPTU', '國立屏東大學（NPTU）'), ('NTUS', '國立臺灣體育運動大學（NTUS）'), ('NTUB', '國立臺北商業大學（NTUB）'), ('NOU', '國立空中大學（NOU）'), ('Other', '其他（Other）')], max_length=200, verbose_name='所屬學校')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='學院')),
                ('faculty_en', models.CharField(blank=True, max_length=100, verbose_name='學院 English')),
                ('name', models.CharField(max_length=200, verbose_name='系所名稱')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='系所名稱 English')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '系所',
                'verbose_name_plural': '系所',
                'db_table': 'users_department',
                'ordering': ['university', 'order', 'id'],
            },
        ),
    ]
