# Generated by Django 6.0.4 on 2026-07-08 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_seed_ncu_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('NTU', '國立臺灣大學（NTU）'), ('NCCU', '國立政治大學（NCCU）'), ('NTHU', '國立清華大學（NTHU）'), ('NYCU', '國立陽明交通大學（NYCU）'), ('NCKU', '國立成功大學（NCKU）'), ('NCHU', '國立中興大學（NCHU）'), ('NCU', '國立中央大學（NCU）'), ('NSYSU', '國立中山大學（NSYSU）'), ('NTNU', '國立臺灣師範大學（NTNU）'), ('NTPU', '國立臺北大學（NTPU）'), ('NUTN', '國立臺南大學（NUTN）'), ('NCYU', '國立嘉義大學（NCYU）'), ('NDHU', '國立東華大學（NDHU）'), ('NCNU', '國立暨南國際大學（NCNU）'), ('NIU', '國立宜蘭大學（NIU）'), ('NUU', '國立聯合大學（NUU）'), ('NTTU', '國立臺東大學（NTTU）'), ('NQU', '國立金門大學（NQU）'), ('NPU', '國立澎湖科技大學（NPU）'), ('NTUST', '國立臺灣科技大學（NTUST）'), ('NTUT', '國立臺北科技大學（NTUT）'), ('NKUST', '國立高雄科技大學（NKUST）'), ('YunTech', '國立雲林科技大學（YunTech）'), ('NPUST', '國立屏東科技大學（NPUST）'), ('NTCUST', '國立臺中科技大學（NTCUST）'), ('NFU', '國立虎尾科技大學（NFU）'), ('NKUHT', '國立高雄餐旅大學（NKUHT）'), ('NKNU', '國立高雄師範大學（NKNU）'), ('NCUE', '國立彰化師範大學（NCUE）'), ('NTUE', '國立臺北教育大學（NTUE）'), ('NTCU', '國立臺中教育大學（NTCU）'), ('NPTU', '國立屏東大學（NPTU）'), ('NTUS', '國立臺灣體育運動大學（NTUS）'), ('NTUB', '國立臺北商業大學（NTUB）'), ('NOU', '國立空中大學（NOU）'), ('Other', '其他（Other）')], max_length=200, verbose_name='學校')),
                ('nationality', models.CharField(blank=True, choices=[('Japan', '日本'), ('Korea', '韓國'), ('Macau', '澳門'), ('Hong Kong', '香港'), ('Mongolia', '蒙古'), ('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Singapore', '新加坡'), ('India', '印度'), ('Pakistan', '巴基斯坦'), ('Bangladesh', '孟加拉'), ('Saudi Arabia', '沙烏地阿拉伯'), ('UAE', '阿拉伯聯合大公國'), ('Turkey', '土耳其'), ('UK', '英國'), ('France', '法國'), ('Germany', '德國'), ('Italy', '義大利'), ('Spain', '西班牙'), ('USA', '美國'), ('Canada', '加拿大'), ('Brazil', '巴西'), ('Mexico', '墨西哥'), ('Argentina', '阿根廷'), ('South Africa', '南非'), ('Egypt', '埃及'), ('Nigeria', '奈及利亞'), ('Australia', '澳洲'), ('New Zealand', '紐西蘭'), ('Other', '其他')], max_length=50, verbose_name='國籍')),
                ('program', models.CharField(blank=True, max_length=200, verbose_name='就讀系所 / 學程')),
                ('content', models.TextField(max_length=1000, verbose_name='分享內容')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='推薦指數')),
                ('is_active', models.BooleanField(default=True, help_text='管理員可取消勾選以下架不當內容', verbose_name='是否顯示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發佈時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_shares', to=settings.AUTH_USER_MODEL, verbose_name='發佈者')),
            ],
            options={
                'verbose_name': '學長姐分享',
                'verbose_name_plural': '學長姐分享',
                'db_table': 'users_alumni_share',
                'ordering': ['-created_at'],
            },
        ),
    ]
