# Generated by Django 6.0.4 on 2026-07-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alumnishare'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='discipline',
            field=models.CharField(blank=True, choices=[('info', '資訊學群'), ('engineering', '工程學群'), ('math_science', '數理化學群'), ('medical', '醫藥衛生學群'), ('life_science', '生命科學學群'), ('bio_resource', '生物資源學群'), ('earth_env', '地球與環境學群'), ('architecture', '建築與設計學群'), ('arts', '藝術學群'), ('social_psy', '社會與心理學群'), ('mass_comm', '大眾傳播學群'), ('foreign_lang', '外語學群'), ('humanities', '文史哲學群'), ('education', '教育學群'), ('law_politics', '法政學群'), ('management', '管理學群'), ('finance', '財經學群'), ('recreation_sport', '遊憩與運動學群')], help_text='AI 小老師會依此學群載入對應的課業輔導知識', max_length=30, verbose_name='所屬學群'),
        ),
    ]
