# Generated by Django 6.0.4 on 2026-07-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_set_department_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnishare',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='標題'),
        ),
    ]
