# Generated by Django 6.0.4 on 2026-07-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alumnishare_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NTU', '國立臺灣大學（NTU）'), ('NCCU', '國立政治大學（NCCU）'), ('NTHU', '國立清華大學（NTHU）'), ('NYCU', '國立陽明交通大學（NYCU）'), ('NCKU', '國立成功大學（NCKU）'), ('NCHU', '國立中興大學（NCHU）'), ('NCU', '國立中央大學（NCU）'), ('NSYSU', '國立中山大學（NSYSU）'), ('NTNU', '國立臺灣師範大學（NTNU）'), ('NTPU', '國立臺北大學（NTPU）'), ('NUTN', '國立臺南大學（NUTN）'), ('NCYU', '國立嘉義大學（NCYU）'), ('NDHU', '國立東華大學（NDHU）'), ('NCNU', '國立暨南國際大學（NCNU）'), ('NIU', '國立宜蘭大學（NIU）'), ('NUU', '國立聯合大學（NUU）'), ('NTTU', '國立臺東大學（NTTU）'), ('NQU', '國立金門大學（NQU）'), ('NPU', '國立澎湖科技大學（NPU）'), ('NTUST', '國立臺灣科技大學（NTUST）'), ('NTUT', '國立臺北科技大學（NTUT）'), ('NKUST', '國立高雄科技大學（NKUST）'), ('YunTech', '國立雲林科技大學（YunTech）'), ('NPUST', '國立屏東科技大學（NPUST）'), ('NTCUST', '國立臺中科技大學（NTCUST）'), ('NFU', '國立虎尾科技大學（NFU）'), ('NKUHT', '國立高雄餐旅大學（NKUHT）'), ('NKNU', '國立高雄師範大學（NKNU）'), ('NCUE', '國立彰化師範大學（NCUE）'), ('NTUE', '國立臺北教育大學（NTUE）'), ('NTCU', '國立臺中教育大學（NTCU）'), ('NPTU', '國立屏東大學（NPTU）'), ('NTUS', '國立臺灣體育運動大學（NTUS）'), ('NTUB', '國立臺北商業大學（NTUB）'), ('NOU', '國立空中大學（NOU）'), ('Other', '其他（Other）')], max_length=200, unique=True, verbose_name='學校代碼')),
                ('name', models.CharField(max_length=200, verbose_name='學校全名')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='學校英文全名')),
                ('aliases', models.CharField(blank=True, help_text='以逗號分隔，學生可能使用的所有稱呼，例如：中央,中大,NCU,中央大學,National Central University', max_length=500, verbose_name='簡稱 / 別名')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='校本部地址')),
                ('main_tel', models.CharField(blank=True, max_length=50, verbose_name='學校總機')),
                ('website', models.URLField(blank=True, verbose_name='官方網站')),
                ('intl_office_name', models.CharField(blank=True, help_text='各校名稱不同，例如：國際事務處 / 國際處 / 國際學生事務組', max_length=100, verbose_name='國際事務處名稱')),
                ('intl_office_tel', models.CharField(blank=True, max_length=50, verbose_name='國際處電話')),
                ('intl_office_ext', models.CharField(blank=True, max_length=20, verbose_name='國際處分機')),
                ('intl_office_url', models.URLField(blank=True, verbose_name='國際處網站')),
                ('calendar_url', models.URLField(blank=True, verbose_name='行事曆網址')),
                ('admission_url', models.URLField(blank=True, verbose_name='境外生招生 / 入學申請網址')),
                ('last_verified_at', models.DateField(blank=True, help_text='最後一次對照官網確認此資料仍正確的日期，留空代表尚未查核', null=True, verbose_name='最後查核日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '學校資料',
                'verbose_name_plural': '學校資料',
                'db_table': 'users_school',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='單位名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='單位英文名稱')),
                ('aliases', models.CharField(blank=True, help_text='以逗號分隔，例如：校長室,校長辦公室,President Office', max_length=300, verbose_name='別名')),
                ('location', models.CharField(blank=True, help_text='例如：行政大樓 2 樓 201 室', max_length=200, verbose_name='位置')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='電話')),
                ('ext', models.CharField(blank=True, max_length=20, verbose_name='分機')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('url', models.URLField(blank=True, verbose_name='單位網頁')),
                ('office_hours', models.CharField(blank=True, max_length=200, verbose_name='服務時間')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='users.school', verbose_name='所屬學校')),
            ],
            options={
                'verbose_name': '校內單位',
                'verbose_name_plural': '校內單位',
                'db_table': 'users_school_unit',
                'ordering': ['school', 'order', 'id'],
            },
        ),
    ]
