# Generated by Django 6.0.4 on 2026-08-08 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_school_schoolunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('portal', '校務行政系統 Portal'), ('lms', '數位學習平台'), ('course', '選課系統'), ('mail', '學生信箱'), ('dorm', '住宿服務系統'), ('library', '圖書館系統'), ('other', '其他系統')], default='other', max_length=20, verbose_name='系統類型')),
                ('name', models.CharField(max_length=100, verbose_name='系統名稱')),
                ('aliases', models.CharField(blank=True, help_text='學生實際會講的說法，以逗號分隔，例如：eeclass,數位學習平台,線上課程', max_length=300, verbose_name='別名')),
                ('url', models.URLField(verbose_name='網址')),
                ('note', models.CharField(blank=True, help_text='例如登入帳號規則、僅限校內網路使用等', max_length=200, verbose_name='備註')),
                ('last_checked_at', models.DateField(blank=True, help_text='由 check_school_links 指令自動更新；連結失效時會在後台標示', null=True, verbose_name='最後連線檢查日期')),
                ('is_reachable', models.BooleanField(default=True, help_text='最後一次檢查時是否正常回應；False 代表連結可能已失效需人工確認', verbose_name='連結是否可連通')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='users.school', verbose_name='所屬學校')),
            ],
            options={
                'verbose_name': '學校線上系統連結',
                'verbose_name_plural': '學校線上系統連結',
                'db_table': 'users_school_link',
                'ordering': ['school', 'order', 'id'],
            },
        ),
    ]
