# Generated by Django 6.0.4 on 2026-08-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_schoollink'),
        ('users', '0018_studentprofile_has_received_welcome_chat'),
    ]

    operations = [
    ]
