# -*- coding: utf-8 -*-
import polib, sys

translations = {
    '課務資訊': {'en':'Course Registration Info','vi':'Thông tin Đăng ký Khóa học','id':'Info Registrasi Mata Kuliah','ms':'Maklumat Pendaftaran Kursus','th':'ข้อมูลการลงทะเบียนวิชาเรียน','ja':'履修情報','ko':'수업 등록 정보','my':'သင်တန်းမှတ်ပုံတင်ရေးသတင်းအချက်အလက်'},
    '選課・加退選・停修・抵免': {'en':'Course Selection · Add/Drop · Withdrawal · Credit Exemption','vi':'Chọn khóa · Thêm/Rớt · Rút · Miễn tín chỉ','id':'Pilih Mata Kuliah · Tambah/Batal · Undur Diri · Pembebasan Kredit','ms':'Pilih Kursus · Tambah/Tanggal · Penarikan · Pengecualian Kredit','th':'เลือกวิชา · เพิ่ม/ถอน · ถอนวิชา · ยกเว้นเครดิต','ja':'履修登録・履修追加削除・停修・単位免除','ko':'수강신청 · 추가/취소 · 수강 철회 · 학점 면제','my':'သင်တန်းရွေးချယ်ခြင်း · ထည့်/ဖြုတ်ခြင်း · ရပ်ဆိုင်းခြင်း · ခရက်ဒစ်ကင်းလွတ်ခွင့်'},
    '中央大學選課系統、學期課務日程與各項申辦流程整理。日程以課務組公告為準，每學期略有調整。': {'en':'NCU course registration system, semester schedule, and application procedures. Dates are subject to official announcements by the Academic Affairs Division and may vary each semester.','vi':'Hệ thống đăng ký khóa học NCU, lịch học kỳ và quy trình đăng ký. Ngày tháng theo thông báo chính thức của Phòng Học vụ và có thể thay đổi mỗi học kỳ.','id':'Sistem registrasi mata kuliah NCU, jadwal semester, dan prosedur pendaftaran. Tanggal mengikuti pengumuman resmi Divisi Urusan Akademik dan dapat berubah setiap semester.','ms':'Sistem pendaftaran kursus NCU, jadual semester, dan prosedur permohonan. Tarikh tertakluk kepada pengumuman rasmi Bahagian Hal Ehwal Akademik dan boleh berubah setiap semester.','th':'ระบบลงทะเบียนวิชาเรียนของ NCU ตารางประจำภาคเรียน และขั้นตอนการสมัคร วันที่อ้างอิงจากประกาศอย่างเป็นทางการของฝ่ายวิชาการ และอาจมีการเปลี่ยนแปลงในแต่ละภาคเรียน','ja':'NCU履修登録システム、学期課務日程と各申請手続きの案内。日程は課務組の正式発表を基準とし、学期毎に調整される場合があります。','ko':'NCU 수강신청 시스템, 학기 일정 및 신청 절차 안내. 날짜는 교학처 공식 공지를 기준으로 하며 학기마다 다를 수 있습니다.','my':'NCU သင်တန်းမှတ်ပုံတင်ရေးစနစ်၊ နှစ်ဝက်အချိန်ဇယားနှင့် လျှောက်ထားသည့်လုပ်ငန်းစဉ်များ။ ရက်စွဲများသည် ပညာရေးရေးရာဌာန ထုတ်ပြန်ကြေညာချက်အတိုင်းဖြစ်ပြီး နှစ်ဝက်တိုင်း ကွဲပြားနိုင်သည်။'},
    '日程請以課務組最新公告為準：': {'en':'Please refer to the latest announcement from the Academic Affairs Division for schedules:','vi':'Vui lòng tham khảo thông báo mới nhất từ Phòng Học vụ về lịch:','id':'Silakan merujuk ke pengumuman terbaru dari Divisi Urusan Akademik untuk jadwal:','ms':'Sila rujuk pengumuman terkini dari Bahagian Hal Ehwal Akademik untuk jadual:','th':'กรุณาดูประกาศล่าสุดจากฝ่ายวิชาการสำหรับตาราง:','ja':'日程は課務組の最新発表をご確認ください：','ko':'일정은 교학처 최신 공지를 기준으로 해주세요:','my':'အချိန်ဇယားများအတွက် ပညာရေးရေးရာဌာန၏ နောက်ဆုံးထုတ်ပြန်ကြေညာချက်ကို ကိုးကားပါ:'},
    '以下日期以 114 學年度第 2 學期為例，每學期日程不同。請至': {'en':'The dates below are based on Academic Year 114, Semester 2 as an example. Schedules differ each semester. Please visit','vi':'Các ngày dưới đây dựa trên Năm học 114, Học kỳ 2 làm ví dụ. Lịch khác nhau mỗi học kỳ. Vui lòng truy cập','id':'Tanggal di bawah ini berdasarkan Tahun Akademik 114, Semester 2 sebagai contoh. Jadwal berbeda setiap semester. Silakan kunjungi','ms':'Tarikh di bawah adalah berdasarkan Tahun Akademik 114, Semester 2 sebagai contoh. Jadual berbeza setiap semester. Sila lawati','th':'วันที่ด้านล่างนี้อ้างอิงจากปีการศึกษา 114 ภาคเรียนที่ 2 เป็นตัวอย่าง ตารางแตกต่างกันในแต่ละภาคเรียน กรุณาไปที่','ja':'以下の日程は114学年度第2学期を例として示しています。学期毎に異なりますので、','ko':'아래 날짜는 114학년도 2학기를 예시로 한 것입니다. 학기마다 일정이 다릅니다. 방문해 주세요','my':'အောက်ပါရက်စွဲများသည် ၁၁၄ ပညာသင်နှစ် ဒုတိယနှစ်ဝက်ကို ဥပမာအဖြစ်သုံးသည်။ နှစ်ဝက်တိုင်း အချိန်ဇယားကွဲပြားသည်။'},
    '課務組官網 ↗': {'en':'Academic Affairs Division Website ↗','vi':'Trang web Phòng Học vụ ↗','id':'Situs Web Divisi Urusan Akademik ↗','ms':'Laman Web Bahagian Hal Ehwal Akademik ↗','th':'เว็บไซต์ฝ่ายวิชาการ ↗','ja':'課務組公式サイト ↗','ko':'교학처 공식 홈페이지 ↗','my':'ပညာရေးရေးရာဌာန ဝဘ်ဆိုဒ် ↗'},
    '查看最新學期日程表。': {'en':'to view the latest semester schedule.','vi':'để xem lịch học kỳ mới nhất.','id':'untuk melihat jadwal semester terbaru.','ms':'untuk melihat jadual semester terkini.','th':'เพื่อดูตารางประจำภาคเรียนล่าสุด','ja':'最新の学期日程をご確認ください。','ko':'최신 학기 일정을 확인하세요.','my':'နောက်ဆုံးနှစ်ဝက်အချိန်ဇယားကို ကြည့်ရန်'},
    '學期課務日程（114-2 為例）': {'en':'Semester Course Schedule (AY114-2 Example)','vi':'Lịch Học kỳ (Ví dụ NĐ114-2)','id':'Jadwal Semester (Contoh TA114-2)','ms':'Jadual Semester (Contoh TA114-2)','th':'ตารางประจำภาคเรียน (ตัวอย่าง 114-2)','ja':'学期課務日程（114-2を例として）','ko':'학기 과목 일정 (114-2 예시)','my':'နှစ်ဝက်သင်တန်းအချိန်ဇယား (၁၁၄-၂ ဥပမာ)'},
    '初選': {'en':'Initial Registration','vi':'Đăng ký ban đầu','id':'Registrasi Awal','ms':'Pendaftaran Awal','th':'การลงทะเบียนครั้งแรก','ja':'初回履修登録','ko':'초기 수강신청','my':'ကနဦးမှတ်ပုံတင်ခြင်း'},
    '加退選': {'en':'Add/Drop','vi':'Thêm/Bỏ','id':'Tambah/Batal','ms':'Tambah/Tanggal','th':'เพิ่ม/ถอนวิชา','ja':'履修追加・削除','ko':'추가/취소','my':'ထည့်/ဖြုတ်ခြင်း'},
    '人工加退選': {'en':'Manual Add/Drop','vi':'Thêm/Bỏ thủ công','id':'Tambah/Batal Manual','ms':'Tambah/Tanggal Manual','th':'เพิ่ม/ถอนวิชาด้วยตนเอง','ja':'手動履修追加・削除','ko':'수동 추가/취소','my':'လက်တင်ထည့်/ဖြုတ်ခြင်း'},
    '手續費 NT$100': {'en':'Processing fee NT$100','vi':'Phí xử lý NT$100','id':'Biaya proses NT$100','ms':'Yuran pemprosesan NT$100','th':'ค่าธรรมเนียม NT$100','ja':'手数料 NT$100','ko':'수수료 NT$100','my':'လုပ်ငန်းစဉ်ကြေး NT$100'},
    '確認結果': {'en':'Confirm Results','vi':'Xác nhận kết quả','id':'Konfirmasi Hasil','ms':'Sahkan Keputusan','th':'ยืนยันผล','ja':'結果確認','ko':'결과 확인','my':'ရလဒ်အတည်ပြုခြင်း'},
    '繳學分費': {'en':'Pay Credit Fees','vi':'Thanh toán phí tín chỉ','id':'Bayar Biaya SKS','ms':'Bayar Yuran Kredit','th':'ชำระค่าหน่วยกิต','ja':'学費（単位費用）支払い','ko':'학점 수수료 납부','my':'ခရက်ဒစ်ကြေး ပေးချေပါ'},
    '停修': {'en':'Course Withdrawal','vi':'Rút khóa học','id':'Penarikan Mata Kuliah','ms':'Penarikan Kursus','th':'การถอนวิชา','ja':'停修（授業取り下げ）','ko':'수강 철회','my':'သင်တန်းရပ်ဆိုင်းခြင်း'},
    '截止': {'en':'Deadline','vi':'Hết hạn','id':'Batas Waktu','ms':'Tamat Tempoh','th':'กำหนดส่ง','ja':'締切','ko':'마감','my':'သတ်မှတ်ရက်'},
    '選課系統入口': {'en':'Course Registration System','vi':'Hệ thống Đăng ký Khóa học','id':'Sistem Registrasi Mata Kuliah','ms':'Sistem Pendaftaran Kursus','th':'ระบบลงทะเบียนวิชาเรียน','ja':'履修登録システム','ko':'수강신청 시스템','my':'သင်တန်းမှတ်ပုံတင်ရေးစနစ်'},
    '選課系統：': {'en':'Course Registration System:','vi':'Hệ thống đăng ký khóa học:','id':'Sistem Registrasi:','ms':'Sistem Pendaftaran:','th':'ระบบลงทะเบียน:','ja':'履修登録システム：','ko':'수강신청 시스템:','my':'မှတ်ပုံတင်ရေးစနစ်:'},
    'SPARC（計中）帳號登入': {'en':'Log in with your SPARC (Computer Center) account','vi':'Đăng nhập bằng tài khoản SPARC (Trung tâm Máy tính)','id':'Masuk dengan akun SPARC (Pusat Komputer)','ms':'Log masuk dengan akaun SPARC (Pusat Komputer)','th':'เข้าสู่ระบบด้วยบัญชี SPARC (ศูนย์คอมพิวเตอร์)','ja':'SPARC（計算機センター）アカウントでログイン','ko':'SPARC (컴퓨터 센터) 계정으로 로그인','my':'SPARC (ကွန်ပြူတာဌာန) အကောင့်ဖြင့် ဝင်ရောက်ပါ'},
    '每日 07:00–09:00 系統進行資料備份，': {'en':'The system performs data backup daily from 07:00–09:00. ','vi':'Hệ thống sao lưu dữ liệu hàng ngày từ 07:00–09:00. ','id':'Sistem melakukan backup data setiap hari pukul 07:00–09:00. ','ms':'Sistem membuat sandaran data setiap hari dari 07:00–09:00. ','th':'ระบบทำการสำรองข้อมูลทุกวันเวลา 07:00–09:00 ','ja':'システムは毎日07:00〜09:00にデータバックアップを行います。','ko':'시스템이 매일 07:00–09:00에 데이터 백업을 수행합니다. ','my':'စနစ်သည် နေ့တိုင်း ၀၇:၀၀–၀၉:၀၀ တွင် ဒေတာမိတ္တူကူးသည်။ '},
    '此時段請勿操作選課': {'en':'Please do not use the system during this time','vi':'Vui lòng không sử dụng hệ thống trong thời gian này','id':'Jangan gunakan sistem selama waktu ini','ms':'Jangan gunakan sistem semasa masa ini','th':'กรุณาอย่าเข้าใช้ระบบในช่วงเวลานี้','ja':'この時間帯は履修登録システムを操作しないでください','ko':'이 시간에는 시스템을 사용하지 마세요','my':'ဤအချိန်တွင် စနစ်ကို မသုံးပါနှင့်'},
    '路徑：': {'en':'Path:','vi':'Đường dẫn:','id':'Jalur:','ms':'Laluan:','th':'เส้นทาง:','ja':'パス：','ko':'경로:','my':'လမ်းကြောင်း:'},
    'NCU Portal → 學生服務 → 教務相關服務 → 選課系統': {'en':'NCU Portal → Student Services → Academic Services → Course Registration','vi':'NCU Portal → Dịch vụ sinh viên → Dịch vụ học vụ → Đăng ký khóa học','id':'NCU Portal → Layanan Mahasiswa → Layanan Akademik → Registrasi Mata Kuliah','ms':'NCU Portal → Perkhidmatan Pelajar → Perkhidmatan Akademik → Pendaftaran Kursus','th':'NCU Portal → บริการนักศึกษา → บริการวิชาการ → ลงทะเบียนวิชาเรียน','ja':'NCU Portal → 学生サービス → 教務関連サービス → 履修登録システム','ko':'NCU 포털 → 학생 서비스 → 교학 관련 서비스 → 수강신청','my':'NCU Portal → ကျောင်းသားဝန်ဆောင်မှု → ပညာရေးဝန်ဆောင်မှု → သင်တန်းမှတ်ပုံတင်ရေး'},
    '各階段說明': {'en':'Stage Descriptions','vi':'Mô tả từng giai đoạn','id':'Deskripsi Setiap Tahap','ms':'Penerangan Setiap Peringkat','th':'คำอธิบายแต่ละขั้นตอน','ja':'各段階の説明','ko':'단계별 설명','my':'အဆင့်တစ်ခုချင်းစီ ရှင်းလင်းချက်'},
    '各系所必修課程通常已預設預選，若已申請抵免或提前修畢，請自行退選。': {'en':'Required courses for each department are usually pre-selected. If you have applied for credit exemption or completed them early, please drop them yourself.','vi':'Các môn bắt buộc thường được đăng ký trước. Nếu bạn đã xin miễn tín chỉ hoặc hoàn thành trước, hãy tự bỏ đăng ký.','id':'Mata kuliah wajib biasanya sudah dipilihkan sebelumnya. Jika kamu sudah mengajukan pembebasan kredit atau menyelesaikannya lebih awal, batalkan sendiri.','ms':'Kursus wajib biasanya telah dipilih terlebih dahulu. Jika anda telah memohon pengecualian kredit atau menamatkannya lebih awal, sila tanggalkan sendiri.','th':'วิชาบังคับของแต่ละภาควิชามักถูกเลือกไว้ล่วงหน้า หากคุณขอยกเว้นเครดิตหรือเรียนจบก่อน กรุณาถอนวิชาด้วยตนเอง','ja':'各学科の必修科目は通常あらかじめ登録されています。単位免除申請済みまたは先修完了の場合は自分で削除してください。','ko':'각 학과의 필수 과목은 보통 사전 등록되어 있습니다. 학점 면제를 신청했거나 이미 이수한 경우 직접 취소하세요.','my':'ဌာနတစ်ခုချင်းစီ၏ မဖြစ်မနေသင်ရသောသင်တန်းများကို ပုမ်မပြပဲ ရွေးချယ်ထားလေ့ရှိသည်။ ခရက်ဒစ်ကင်းလွတ်ခွင့်တောင်းဆိုထားပါက သို့မဟုတ် ကြိုတင်ပြီးစဲလျှင် ကိုယ်တိုင်ဖြုတ်ပါ။'},
    '務必參加初選，否則遇有人數限制之課程，將喪失優先選擇權。': {'en':'You must participate in initial registration; otherwise you will lose priority for courses with enrollment limits.','vi':'Bạn phải tham gia đăng ký ban đầu; nếu không bạn sẽ mất ưu tiên cho các khóa học có giới hạn đăng ký.','id':'Kamu harus berpartisipasi dalam registrasi awal; jika tidak, kamu akan kehilangan prioritas untuk mata kuliah dengan batas pendaftaran.','ms':'Anda mesti mengambil bahagian dalam pendaftaran awal; jika tidak anda akan kehilangan keutamaan untuk kursus dengan had pendaftaran.','th':'คุณต้องเข้าร่วมการลงทะเบียนครั้งแรก มิฉะนั้นจะสูญเสียสิทธิ์ลำดับความสำคัญสำหรับวิชาที่มีจำนวนจำกัด','ja':'初回履修登録に必ず参加してください。そうしないと、定員制限のある科目の優先選択権を失います。','ko':'반드시 초기 수강신청에 참여해야 합니다. 그렇지 않으면 정원이 있는 과목의 우선권을 잃게 됩니다.','my':'ကနဦးမှတ်ပုံတင်ခြင်းတွင် မဖြစ်မနေ ပါဝင်ရမည်; မဟုတ်ပါက ကန့်သတ်ထားသောသင်တန်းများအတွက် ဦးစားပေးခွင့်ဆုံးရှုံးမည်'},
    '初選截止後批次分發一次，結果於 115/02/03 16:00 前公告。': {'en':'After initial registration closes, results are distributed in one batch and announced before 16:00 on 115/02/03.','vi':'Sau khi đóng đăng ký ban đầu, kết quả được phân phối một lần và công bố trước 16:00 ngày 115/02/03.','id':'Setelah registrasi awal ditutup, hasilnya didistribusikan sekaligus dan diumumkan sebelum pukul 16:00 pada 115/02/03.','ms':'Selepas pendaftaran awal ditutup, keputusan diedarkan sekali dan diumumkan sebelum 16:00 pada 115/02/03.','th':'หลังจากปิดการลงทะเบียนครั้งแรก ผลจะถูกแจกจ่ายครั้งเดียวและประกาศก่อน 16:00 ของวันที่ 115/02/03','ja':'初回登録締切後、一括分配し、115/02/03 16:00前に結果が発表されます。','ko':'초기 수강신청 마감 후 결과가 일괄 배분되어 115/02/03 16:00 이전에 공지됩니다.','my':'ကနဦးမှတ်ပုံတင်ခြင်းပိတ်ပြီးနောက် ရလဒ်များကို တစ်ကြိမ်တည်း ဖြန့်ဝေပြီး ၁၁၅/၀၂/၀၃ ၁၆:၀၀ မတိုင်မီ ကြေညာမည်'},
    '大一上學生不需要導師密碼卡；大一下起每學期初選前須完成導師輔導選課程序（線上操作）。': {'en':'First-semester freshmen do not need an advisor password card. Starting from the second semester, students must complete the advisor-guided course selection procedure (online) before initial registration each semester.','vi':'Sinh viên năm nhất học kỳ 1 không cần thẻ mật khẩu cố vấn. Từ học kỳ 2 trở đi, sinh viên phải hoàn thành thủ tục tư vấn chọn khóa học (trực tuyến) trước mỗi đợt đăng ký ban đầu.','id':'Mahasiswa baru semester pertama tidak membutuhkan kartu sandi penasihat. Mulai semester kedua, mahasiswa harus menyelesaikan prosedur pemilihan mata kuliah yang dipandu penasihat (online) sebelum registrasi awal.','ms':'Pelajar tahun pertama semester pertama tidak memerlukan kad kata laluan penasihat. Bermula semester kedua, pelajar mesti melengkapkan prosedur pemilihan kursus berpandu penasihat (dalam talian) sebelum pendaftaran awal.','th':'นักศึกษาปีหนึ่งเทอมแรกไม่ต้องการบัตรรหัสผ่านอาจารย์ที่ปรึกษา ตั้งแต่เทอมสองเป็นต้นไป นักศึกษาต้องทำขั้นตอนการเลือกวิชาที่ปรึกษา (ออนไลน์) ให้เสร็จก่อนการลงทะเบียนครั้งแรก','ja':'1年次前期の学生はアドバイザーパスワードカード不要。後期以降は毎学期初回登録前にアドバイザー指導による履修手続き（オンライン）を完了してください。','ko':'1학년 1학기 학생은 지도교수 비밀번호 카드가 필요 없습니다. 2학기부터는 매 학기 초기 수강신청 전에 지도교수 상담 수강신청 절차(온라인)를 완료해야 합니다.','my':'ပထမနှစ်ပထမနှစ်ဝက် ကျောင်းသားများသည် ဆရာဝင်ကတ် မလိုအပ်ပါ။ ဒုတိယနှစ်ဝက်မှ စတင်ကာ တစ်နှစ်ဝက်တိုင်း ကနဦးမှတ်ပုံတင်မတိုင်မီ ဆရာမှ လမ်းညွှန်ခြင်းလုပ်ငန်းစဉ် (အွန်လိုင်း) ပြီးအောင်လုပ်ရမည်'},
    '春節期間（02/13–02/22）不開放選課，請注意。': {'en':'Course registration is not available during the Lunar New Year holiday (02/13–02/22). Please take note.','vi':'Đăng ký khóa học không khả dụng trong kỳ nghỉ Tết Âm lịch (02/13–02/22). Vui lòng lưu ý.','id':'Registrasi mata kuliah tidak tersedia selama liburan Tahun Baru Imlek (02/13–02/22). Harap diperhatikan.','ms':'Pendaftaran kursus tidak tersedia semasa cuti Tahun Baru Cina (02/13–02/22). Sila ambil perhatian.','th':'ระบบลงทะเบียนวิชาเรียนจะไม่เปิดในช่วงวันหยุดตรุษจีน (02/13–02/22) กรุณาสังเกต','ja':'春節期間（02/13〜02/22）は履修登録不可。ご注意ください。','ko':'설 연휴(02/13–02/22) 기간에는 수강신청이 불가합니다. 주의하세요.','my':'တရုတ်နှစ်သစ်ကူးရုံးပိတ်ရက် (02/13–02/22) တွင် သင်တန်းမှတ်ပုံတင်ခြင်းကို မပြုလုပ်နိုင်ပါ'},
    '自加退選第 3 日起，系統每日 07:00–09:00 分發一次（處理期間系統暫停），09:00 後可至 ee-class 確認當日中選結果。': {'en':'From the 3rd day of add/drop, the system distributes results once daily at 07:00–09:00 (system paused during processing). After 09:00 you can check the day\'s results on ee-class.','vi':'Từ ngày thứ 3 của giai đoạn thêm/bỏ, hệ thống phân phối kết quả một lần mỗi ngày lúc 07:00–09:00 (hệ thống tạm dừng trong quá trình xử lý). Sau 09:00 bạn có thể kiểm tra kết quả ngày hôm đó trên ee-class.','id':'Mulai hari ke-3 masa tambah/batal, sistem mendistribusikan hasil sekali sehari pukul 07:00–09:00 (sistem dijeda selama pemrosesan). Setelah 09:00 kamu bisa cek hasil hari itu di ee-class.','ms':'Dari hari ke-3 tempoh tambah/tanggal, sistem mengedarkan keputusan sekali sehari pada 07:00–09:00 (sistem dijeda semasa pemprosesan). Selepas 09:00 anda boleh semak keputusan hari itu di ee-class.','th':'ตั้งแต่วันที่ 3 ของการเพิ่ม/ถอน ระบบจะแจกจ่ายผลลัพธ์ครั้งเดียวต่อวันเวลา 07:00–09:00 (ระบบหยุดชั่วคราวระหว่างการประมวลผล) หลัง 09:00 สามารถตรวจสอบผลของวันนั้นได้ที่ ee-class','ja':'加退選3日目以降、システムは毎日07:00〜09:00に一括分配（処理中はシステム停止）。09:00以降にee-classで当日の結果を確認できます。','ko':'추가/취소 3일째부터 시스템이 매일 07:00–09:00에 결과를 일괄 배분합니다(처리 중 시스템 일시 중지). 09:00 이후 ee-class에서 당일 결과를 확인할 수 있습니다.','my':'ထည့်/ဖြုတ်ကာလ ၃ ရက်မြောက်မှ စတင်ကာ စနစ်သည် နေ့တိုင်း ၀၇:၀၀–၀၉:၀၀ တွင် ရလဒ်ဖြန့်ဝေသည် (လုပ်ဆောင်နေစဉ် ရပ်နားသည်)။ ၀၉:၀၀ ပြီးနောက် ee-class တွင် ထိုနေ့ ရလဒ်စစ်ဆေးနိုင်သည်'},
    '落選課程若仍想修習，需再次上網登錄，等候隔日分發，不會自動保留候補。': {'en':'If you still wish to take a course you were not selected for, you must register online again and wait for the next day\'s distribution. Waitlist spots are not held automatically.','vi':'Nếu bạn vẫn muốn học môn không được chọn, hãy đăng ký lại trực tuyến và chờ phân phối ngày hôm sau. Vị trí danh sách chờ không được giữ tự động.','id':'Jika kamu masih ingin mengambil mata kuliah yang tidak dipilih, kamu harus mendaftar ulang secara online dan menunggu distribusi hari berikutnya. Posisi waitlist tidak disimpan otomatis.','ms':'Jika anda masih mahu mengambil kursus yang tidak dipilih, anda perlu mendaftar semula dalam talian dan menunggu pengagihan hari berikutnya. Kedudukan senarai tunggu tidak disimpan secara automatik.','th':'หากคุณยังต้องการเรียนวิชาที่ไม่ถูกเลือก ต้องลงทะเบียนออนไลน์อีกครั้งและรอการแจกจ่ายของวันถัดไป ลิสต์รอไม่ถูกเก็บไว้โดยอัตโนมัติ','ja':'落選した科目をまだ履修したい場合は、再度オンライン登録し翌日の分配を待ってください。補欠は自動的に保持されません。','ko':'탈락한 과목을 아직 수강하고 싶다면 다시 온라인으로 신청하고 다음 날 배분을 기다려야 합니다. 대기 순번은 자동으로 유지되지 않습니다.','my':'ရွေးချယ်မခံရသောသင်တန်းကို ဆက်လက်တက်ရောက်လိုပါက အွန်လိုင်းမှ ထပ်မှတ်ပုံတင်ပြီး နောက်နေ့ ဖြန့်ဝေမှုကို စောင့်ရမည်။ စောင့်စာရင်းကို အလိုအလျောက် မသိမ်းဆည်းပါ'},
    '加退選最後一日請勿加選可能衝堂的課，以免最後一次分發造成衝堂被系統強制退選。': {'en':'On the last day of add/drop, do not add courses that may conflict with your schedule, to avoid being forcibly dropped by the system in the final distribution.','vi':'Vào ngày cuối cùng của thêm/bỏ, đừng thêm các khóa học có thể trùng lịch để tránh bị hệ thống bắt buộc bỏ trong lần phân phối cuối.','id':'Pada hari terakhir tambah/batal, jangan tambahkan mata kuliah yang mungkin bentrok, untuk menghindari dipaksa keluar oleh sistem pada distribusi terakhir.','ms':'Pada hari terakhir tambah/tanggal, jangan tambah kursus yang mungkin berlanggaran, untuk mengelak dipaksa keluar oleh sistem dalam pengagihan terakhir.','th':'ในวันสุดท้ายของการเพิ่ม/ถอน อย่าเพิ่มวิชาที่อาจชนกับตาราง เพื่อหลีกเลี่ยงการถูกระบบบังคับถอนในการแจกจ่ายครั้งสุดท้าย','ja':'加退選最終日は時間割の衝突が生じうる科目は追加しないでください。最終分配で強制退選になる恐れがあります。','ko':'추가/취소 마지막 날에는 시간표가 겹칠 수 있는 과목을 추가하지 마세요. 마지막 배분에서 시스템에 의해 강제 취소될 수 있습니다.','my':'ထည့်/ဖြုတ်ကာလ နောက်ဆုံးနေ့တွင် အချိန်ဇယားနှင့် ထပ်နိုင်သောသင်တန်းများကို မထည့်ပါနှင့်။ နောက်ဆုံး ဖြန့်ဝေမှုတွင် စနစ်မှ အတင်းဖြုတ်ပစ်နိုင်သည်'},
    '課程有設定密碼卡者，須向任課教師索取，每組密碼使用一次即失效。': {'en':'For courses requiring a password card, obtain it from the instructor. Each password can only be used once.','vi':'Đối với các khóa học yêu cầu thẻ mật khẩu, hãy lấy từ giáo viên. Mỗi mật khẩu chỉ dùng được một lần.','id':'Untuk mata kuliah yang membutuhkan kartu sandi, dapatkan dari instruktur. Setiap sandi hanya bisa digunakan sekali.','ms':'Untuk kursus yang memerlukan kad kata laluan, dapatkan daripada pensyarah. Setiap kata laluan hanya boleh digunakan sekali.','th':'สำหรับวิชาที่ต้องการบัตรรหัสผ่าน ขอรับจากอาจารย์ผู้สอน รหัสผ่านแต่ละชุดใช้ได้เพียงครั้งเดียว','ja':'パスワードカードが必要な科目は担当教員から入手してください。各パスワードは一度使用すると無効になります。','ko':'비밀번호 카드가 필요한 과목은 담당 교수에게서 받아야 합니다. 각 비밀번호는 한 번만 사용 가능합니다.','my':'လျှို့ဝှက်ကတ်လိုအပ်သောသင်တန်းများအတွက် ဆရာထံမှ ရယူပါ။ လျှို့ဝှက်နံပါတ်တစ်ခုချင်းစီကို တစ်ကြိမ်သာ သုံးနိုင်သည်'},
    '適用對象：加退選截止後仍有需求者、因衝堂被系統退選後欲重新加選者。': {'en':'Applicable for: those who still need to add/drop after the deadline, and those who were forcibly dropped due to schedule conflicts and wish to re-enroll.','vi':'Áp dụng cho: những ai vẫn cần thêm/bỏ sau thời hạn, và những ai bị bỏ bắt buộc do trùng lịch và muốn đăng ký lại.','id':'Berlaku untuk: yang masih perlu tambah/batal setelah batas waktu, dan yang dipaksa keluar karena bentrok dan ingin mendaftar ulang.','ms':'Terpakai untuk: yang masih perlu tambah/tanggal selepas tarikh akhir, dan yang dipaksa keluar kerana berlanggaran dan ingin mendaftar semula.','th':'สำหรับ: ผู้ที่ยังต้องการเพิ่ม/ถอนหลังจากกำหนดเวลา และผู้ที่ถูกบังคับออกเนื่องจากชนกับตารางและต้องการลงทะเบียนใหม่','ja':'対象者：加退選締切後も変更が必要な者、時間割衝突で強制退選になり再登録希望の者。','ko':'대상: 마감 후 추가/취소가 필요한 학생, 시간표 충돌로 강제 취소되어 재등록을 원하는 학생.','my':'သက်ဆိုင်သူများ: သတ်မှတ်ရက်ပြီးနောက် ထည့်/ဖြုတ်ရန် လိုအပ်သူများ၊ နှင့် အချိန်ဇယားထပ်ကျိုင်မှုကြောင့် အတင်းဖြုတ်ခံရပြီး ပြန်မှတ်ပုံတင်လိုသူများ'},
    '流程：選課系統列印申請表 → 取得任課教師簽章 → 繳 NT$100 手續費（出納組現金 或 課務組悠遊卡扣款）→ 申請表送至課務組。': {'en':'Process: Print application form from the course system → Get instructor signature → Pay NT$100 processing fee (cash at cashier or EasyCard deduction at Academic Affairs) → Submit form to Academic Affairs Division.','vi':'Quy trình: In đơn từ hệ thống → Lấy chữ ký giáo viên → Nộp phí NT$100 (tiền mặt tại quầy thu ngân hoặc thẻ EasyCard tại Phòng Học vụ) → Nộp đơn cho Phòng Học vụ.','id':'Proses: Cetak formulir dari sistem → Dapatkan tanda tangan instruktur → Bayar biaya NT$100 (tunai di kasir atau kartu EasyCard di Divisi Akademik) → Kirim formulir ke Divisi Akademik.','ms':'Proses: Cetak borang dari sistem → Dapatkan tandatangan pensyarah → Bayar yuran NT$100 (tunai di kaunter atau kad EasyCard di Bahagian Akademik) → Serahkan borang ke Bahagian Akademik.','th':'ขั้นตอน: พิมพ์ใบสมัครจากระบบ → รับลายเซ็นอาจารย์ → ชำระค่าธรรมเนียม NT$100 (เงินสดที่เคาน์เตอร์หรือ EasyCard ที่ฝ่ายวิชาการ) → ส่งใบสมัครให้ฝ่ายวิชาการ','ja':'手順：履修システムで申請書を印刷→担当教員のサイン取得→NT$100手数料支払い（出納窓口現金 or 課務組EasyCard）→申請書を課務組に提出。','ko':'절차: 수강신청 시스템에서 신청서 출력 → 담당 교수 서명 획득 → NT$100 수수료 납부 (현금 or EasyCard) → 신청서 교학처 제출.','my':'လုပ်ငန်းစဉ်: စနစ်မှ လျှောက်လွှာပုံနှိပ်ထုတ်ပါ → ဆရာ လက်မှတ်ရယူပါ → NT$100 ကြေး ပေးချေပါ → လျှောက်လွှာကို ပညာရေးရေးရာဌာနသို့ တင်ပါ'},
    '隔日更新至選課系統與 ee-class。': {'en':'Updates are reflected in the course system and ee-class the following day.','vi':'Cập nhật phản ánh trong hệ thống và ee-class vào ngày hôm sau.','id':'Pembaruan tercermin di sistem dan ee-class pada hari berikutnya.','ms':'Kemas kini ditunjukkan dalam sistem dan ee-class pada hari berikutnya.','th':'การอัปเดตจะแสดงในระบบและ ee-class ในวันถัดไป','ja':'翌日に履修システムとee-classに反映されます。','ko':'다음 날 수강신청 시스템과 ee-class에 반영됩니다.','my':'နောက်တစ်ရက် စနစ်နှင့် ee-class တွင် အပ်ဒိတ်ဖြစ်မည်'},
    '找不到教師本人，可由教師授權系辦人員代理蓋章。': {'en':'If the instructor is unavailable, a department staff member authorized by the instructor may stamp on their behalf.','vi':'Nếu giáo viên không có mặt, nhân viên khoa được ủy quyền có thể đóng dấu thay mặt.','id':'Jika instruktur tidak tersedia, staf departemen yang diberi wewenang dapat memberikan stempel atas nama mereka.','ms':'Jika pensyarah tidak hadir, kakitangan jabatan yang diberi kuasa boleh mencop bagi pihak mereka.','th':'หากอาจารย์ไม่อยู่ เจ้าหน้าที่ภาควิชาที่ได้รับอนุญาตสามารถประทับตราแทนได้','ja':'担当教員本人が不在の場合、教員が授権した学科職員が代理で押印できます。','ko':'교수가 없는 경우 교수의 권한을 받은 학과 직원이 대신 도장을 찍을 수 있습니다.','my':'ဆရာမတွေ့ပါက ဆရာမှ ခွင့်ပြုချက်ရသော ဌာနဝန်ထမ်းမှ တံဆိပ်ရိုက်ပေးနိုင်သည်'},
    '確認選課結果': {'en':'Confirm Course Registration Results','vi':'Xác nhận kết quả đăng ký khóa học','id':'Konfirmasi Hasil Registrasi Mata Kuliah','ms':'Sahkan Keputusan Pendaftaran Kursus','th':'ยืนยันผลการลงทะเบียนวิชาเรียน','ja':'履修登録結果の確認','ko':'수강신청 결과 확인','my':'သင်တန်းမှတ်ပုံတင်ရေးရလဒ် အတည်ပြုခြင်း'},
    '路徑：選課系統 → 個人功能表 → 選課結果。': {'en':'Path: Course System → Personal Menu → Registration Results.','vi':'Đường dẫn: Hệ thống khóa học → Menu cá nhân → Kết quả đăng ký.','id':'Jalur: Sistem Mata Kuliah → Menu Pribadi → Hasil Registrasi.','ms':'Laluan: Sistem Kursus → Menu Peribadi → Keputusan Pendaftaran.','th':'เส้นทาง: ระบบวิชาเรียน → เมนูส่วนตัว → ผลการลงทะเบียน','ja':'パス：履修登録システム→個人メニュー→履修結果。','ko':'경로: 수강신청 시스템 → 개인 메뉴 → 신청 결과.','my':'လမ်းကြောင်း: သင်တန်းစနစ် → ကိုယ်ပိုင်မီနူး → မှတ်ပုံတင်ရလဒ်'},
    '依選課辦法，未於期限內確認者以電腦系統為依據，不得異議。請務必確認！': {'en':'Per course registration regulations, those who do not confirm within the deadline are bound by the computer system records and may not dispute. Please confirm without fail!','vi':'Theo quy định đăng ký khóa học, những ai không xác nhận trong thời hạn sẽ bị ràng buộc bởi hồ sơ máy tính và không được khiếu nại. Hãy xác nhận!','id':'Sesuai peraturan registrasi, mereka yang tidak mengkonfirmasi dalam batas waktu terikat oleh catatan sistem komputer dan tidak dapat mengajukan keberatan. Harap konfirmasi!','ms':'Mengikut peraturan pendaftaran kursus, sesiapa yang tidak mengesahkan dalam tempoh tidak boleh membantah rekod sistem komputer. Sila sahkan!','th':'ตามระเบียบการลงทะเบียน ผู้ที่ไม่ยืนยันภายในกำหนดเวลาจะถูกผูกพันโดยบันทึกระบบคอมพิวเตอร์และไม่สามารถโต้แย้งได้ กรุณายืนยันให้แน่ใจ!','ja':'選課規定により、期限内に確認しなかった場合はコンピュータシステムの記録が拠り所となり、異議申し立て不可。必ず確認してください！','ko':'수강신청 규정에 따라 기한 내 확인하지 않은 경우 컴퓨터 시스템 기록에 따르며 이의를 제기할 수 없습니다. 반드시 확인하세요!','my':'သင်တန်းမှတ်ပုံတင်ရေးစည်းကမ်းများအတိုင်း သတ်မှတ်ရက်အတွင်း အတည်မပြုသူများသည် ကွန်ပြူတာမှတ်တမ်းကိုသာ အခြေခံမည်ဖြစ်ပြီး ကန့်ကွက်၍မရပါ။ မဖြစ်မနေ အတည်ပြုပါ!'},
    '如有衝堂/同課號被強制退選，可於 03/10–03/12 辦理人工加退選補救。': {'en':'If you are forcibly dropped due to schedule conflict or duplicate course code, you may use the manual add/drop period (03/10–03/12) to remedy.','vi':'Nếu bạn bị bỏ bắt buộc do trùng lịch hoặc trùng mã khóa, bạn có thể dùng thời gian thêm/bỏ thủ công (03/10–03/12) để khắc phục.','id':'Jika kamu dipaksa keluar karena bentrok atau kode mata kuliah duplikat, kamu bisa menggunakan masa tambah/batal manual (03/10–03/12) untuk memperbaiki.','ms':'Jika anda dipaksa keluar kerana berlanggaran atau kod kursus berganda, anda boleh gunakan tempoh tambah/tanggal manual (03/10–03/12) untuk pemulihan.','th':'หากถูกบังคับออกเนื่องจากชนกับตารางหรือรหัสวิชาซ้ำ สามารถใช้ช่วงเพิ่ม/ถอนด้วยตนเอง (03/10–03/12) เพื่อแก้ไขได้','ja':'時間割衝突や同課番号で強制退選になった場合、手動加退選期間（03/10〜03/12）に対処できます。','ko':'시간표 충돌 또는 동일 과목 코드로 강제 취소된 경우 수동 추가/취소 기간(03/10–03/12)을 이용하여 해결할 수 있습니다.','my':'အချိန်ဇယားထပ်ကိုင်မှု သို့မဟုတ် တူညီသောသင်တန်းကုဒ်ကြောင့် အတင်းဖြုတ်ခံရပါက လက်တင်ထည့်/ဖြုတ်ကာလ (03/10–03/12) ကို သုံး၍ ပြုပြင်နိုင်သည်'},
    '停修（Course Withdrawal）': {'en':'Course Withdrawal','vi':'Rút khóa học (Course Withdrawal)','id':'Penarikan Mata Kuliah (Course Withdrawal)','ms':'Penarikan Kursus (Course Withdrawal)','th':'การถอนวิชา (Course Withdrawal)','ja':'停修（コース取り下げ）','ko':'수강 철회 (Course Withdrawal)','my':'သင်တန်းရပ်ဆိုင်းခြင်း (Course Withdrawal)'},
    'W 成績': {'en':'W Grade','vi':'Điểm W','id':'Nilai W','ms':'Gred W','th':'เกรด W','ja':'W評価','ko':'W 학점','my':'W ရမှတ်'},
    '一學期以一科為限，停修後學分數不得低於最低應修學分（大一至大三 16 學分、大四 9 學分）。': {'en':'Limited to one course per semester. After withdrawal, remaining credits must not fall below the minimum required (16 for years 1–3, 9 for year 4).','vi':'Giới hạn một môn mỗi học kỳ. Sau khi rút, tín chỉ còn lại không được thấp hơn mức tối thiểu (16 cho năm 1–3, 9 cho năm 4).','id':'Dibatasi satu mata kuliah per semester. Setelah penarikan, kredit yang tersisa tidak boleh kurang dari minimum (16 untuk tahun 1–3, 9 untuk tahun 4).','ms':'Terhad kepada satu kursus setiap semester. Selepas penarikan, kredit yang tinggal tidak boleh kurang dari minimum (16 untuk tahun 1–3, 9 untuk tahun 4).','th':'จำกัดหนึ่งวิชาต่อภาคเรียน หลังจากถอนวิชา หน่วยกิตที่เหลือต้องไม่ต่ำกว่าขั้นต่ำ (16 หน่วยกิตสำหรับปี 1–3, 9 หน่วยกิตสำหรับปี 4)','ja':'1学期に1科目まで。停修後の残単位は最低修得単位数以上であること（1〜3年：16単位、4年：9単位）。','ko':'학기당 1과목 제한. 철회 후 잔여 학점이 최소 이수 학점 이하가 되어서는 안 됩니다(1–3학년 16학점, 4학년 9학점).','my':'တစ်နှစ်ဝက်လျှင် တစ်သင်တန်းသာ ခွင့်ပြုသည်။ ရပ်ဆိုင်းပြီးနောက် ကျန်ရှိသောခရက်ဒစ်သည် အနည်းဆုံးလိုအပ်သောအောက် မကျောင်းနိုင် (ပထမ–တတိယနှစ် ၁၆ ခရက်ဒစ်၊ စတုတ္ထနှစ် ၉ ခရက်ဒစ်)'},
    '停修不退學分費，成績單上以「停修 / W」登錄，不計入當學期所修學分數。': {'en':'No credit fee refund for withdrawal. The transcript records "Withdrawal / W" and it does not count toward the semester\'s credit total.','vi':'Không hoàn phí tín chỉ khi rút. Bảng điểm ghi "Rút / W" và không tính vào tổng tín chỉ của học kỳ.','id':'Tidak ada pengembalian biaya kredit untuk penarikan. Transkrip mencatat "Penarikan / W" dan tidak dihitung ke total kredit semester.','ms':'Tiada bayaran balik yuran kredit untuk penarikan. Transkrip merekodkan "Penarikan / W" dan tidak dikira dalam jumlah kredit semester.','th':'ไม่มีการคืนค่าธรรมเนียมสำหรับการถอนวิชา ใบแสดงผลการเรียนจะบันทึก "ถอนวิชา / W" และไม่นับรวมในจำนวนหน่วยกิตของภาคเรียน','ja':'停修しても学費（単位費用）の返還なし。成績証明書には「停修 / W」と記録され、当学期の履修単位数に含まれません。','ko':'철회 시 학점 수수료 환불 없음. 성적표에 "철회 / W"로 기록되며 학기 학점 합계에 포함되지 않습니다.','my':'ရပ်ဆိုင်းသောသင်တန်းအတွက် ခရက်ဒစ်ကြေး မပြန်အမ်းပါ။ ရမှတ်မှတ်တမ်းတွင် "ရပ်ဆိုင်း / W" ဟု မှတ်တမ်းတင်ပြီး နှစ်ဝက် ခရက်ဒစ်ပေါင်းစုတွင် မပါဝင်ပါ'},
    '流程：選課系統列印停修申請表 → 任課教師及系所主管簽章 → 送至課務組。': {'en':'Process: Print withdrawal application from the course system → Get signatures from instructor and department head → Submit to Academic Affairs Division.','vi':'Quy trình: In đơn rút từ hệ thống → Lấy chữ ký giáo viên và trưởng khoa → Nộp cho Phòng Học vụ.','id':'Proses: Cetak formulir penarikan dari sistem → Dapatkan tanda tangan instruktur dan kepala departemen → Kirim ke Divisi Akademik.','ms':'Proses: Cetak borang penarikan dari sistem → Dapatkan tandatangan pensyarah dan ketua jabatan → Serahkan ke Bahagian Akademik.','th':'ขั้นตอน: พิมพ์ใบสมัครถอนวิชาจากระบบ → รับลายเซ็นอาจารย์และหัวหน้าภาควิชา → ส่งให้ฝ่ายวิชาการ','ja':'手順：履修システムで停修申請書を印刷→担当教員と学科長のサイン→課務組に提出。','ko':'절차: 수강신청 시스템에서 철회 신청서 출력 → 담당 교수 및 학과장 서명 획득 → 교학처 제출.','my':'လုပ်ငန်းစဉ်: စနစ်မှ ရပ်ဆိုင်းလျှောက်လွှာပုံနှိပ်ပါ → ဆရာနှင့် ဌာနမှူးလက်မှတ်ရယူပါ → ပညာရေးရေးရာဌာနသို့ တင်ပါ'},
    '已辦理減修者不得再辦理停修。': {'en':'Students who have already applied for reduced credit load may not also apply for course withdrawal.','vi':'Sinh viên đã đăng ký giảm tải tín chỉ không được đăng ký rút khóa học thêm.','id':'Mahasiswa yang sudah mengajukan pengurangan kredit tidak boleh mengajukan penarikan mata kuliah.','ms':'Pelajar yang telah memohon pengurangan kredit tidak boleh memohon penarikan kursus.','th':'นักศึกษาที่ยื่นขอลดหน่วยกิตแล้วจะไม่สามารถยื่นขอถอนวิชาได้อีก','ja':'既に減修申請をした者は停修申請不可。','ko':'학점 감축을 이미 신청한 학생은 수강 철회를 추가로 신청할 수 없습니다.','my':'ခရက်ဒစ်လျှော့ချရန် ဦးစွာလျှောက်ထားသောကျောင်းသားများသည် သင်တန်းရပ်ဆိုင်းခြင်းကို ထပ်မံ လျှောက်၍မရ'},
    '重要規定': {'en':'Important Regulations','vi':'Quy định quan trọng','id':'Peraturan Penting','ms':'Peraturan Penting','th':'ข้อบังคับสำคัญ','ja':'重要規定','ko':'중요 규정','my':'အရေးကြီးသောစည်းမျဉ်းများ'},
    '最低修課學分：': {'en':'Minimum Credits:','vi':'Tín chỉ tối thiểu:','id':'Kredit Minimum:','ms':'Kredit Minimum:','th':'หน่วยกิตขั้นต่ำ:','ja':'最低履修単位数：','ko':'최소 학점:','my':'အနည်းဆုံးခရက်ဒစ်:'},
    '大一至大三每學期至少修 16 學分；大四每學期至少 9 學分。未達標者需辦理減修（需導師與系主任同意），否則依規定令退學。': {'en':'Years 1–3 must take at least 16 credits per semester; Year 4 at least 9. Those falling short must apply for credit reduction (with advisor and department head approval), otherwise may be subject to dismissal.','vi':'Năm 1–3 phải học ít nhất 16 tín chỉ mỗi học kỳ; Năm 4 ít nhất 9. Những người không đủ phải đăng ký giảm tải (với sự chấp thuận của cố vấn và trưởng khoa), nếu không có thể bị buộc thôi học.','id':'Tahun 1–3 harus mengambil minimal 16 kredit per semester; Tahun 4 minimal 9. Yang kurang harus mengajukan pengurangan kredit (dengan persetujuan penasihat dan kepala departemen), jika tidak dapat dikeluarkan.','ms':'Tahun 1–3 mesti mengambil sekurang-kurangnya 16 kredit setiap semester; Tahun 4 sekurang-kurangnya 9. Yang tidak mencukupi mesti memohon pengurangan kredit (dengan kelulusan penasihat dan ketua jabatan), jika tidak boleh dibuang.','th':'ปี 1–3 ต้องลงทะเบียนอย่างน้อย 16 หน่วยกิตต่อภาคเรียน ปี 4 อย่างน้อย 9 หน่วยกิต ผู้ที่ไม่ถึงต้องยื่นขอลดหน่วยกิต (ต้องได้รับความเห็นชอบจากอาจารย์ที่ปรึกษาและหัวหน้าภาควิชา) มิฉะนั้นอาจถูกไล่ออก','ja':'1〜3年：毎学期最低16単位、4年：最低9単位。未達者は減修申請要（指導教員・学科長の同意必要）、さもなくば規定により退学。','ko':'1–3학년: 학기당 최소 16학점, 4학년: 최소 9학점. 미달 시 학점 감축 신청 필요(지도교수 및 학과장 동의 필요), 미신청 시 규정에 따라 제적 가능.','my':'ပထမ–တတိယနှစ်: တစ်နှစ်ဝက်လျှင် အနည်းဆုံး ၁၆ ခရက်ဒစ်; စတုတ္ထနှစ်: အနည်းဆုံး ၉ ခရက်ဒစ်။ မမီသူများသည် ခရက်ဒစ်လျှော့ချမှုကို လျှောက်ရမည် (ဆရာနှင့် ဌာနမှူး ခွင့်ပြုချက်လိုသည်)'},
    '衝堂 / 同課號：': {'en':'Schedule Conflict / Duplicate Course Code:','vi':'Xung đột lịch / Mã khóa trùng:','id':'Bentrok / Kode Mata Kuliah Duplikat:','ms':'Berlanggaran / Kod Kursus Berganda:','th':'ชนตาราง / รหัสวิชาซ้ำ:','ja':'時間割衝突 / 同課番号：','ko':'시간표 충돌 / 동일 과목 코드:','my':'အချိန်ဇယားထပ်ကိုင်မှု / တူညီသောသင်တန်းကုဒ်:'},
    '加退選截止後若仍有衝堂或重複課號，課務組將全部強制退選。請在截止前自行處理，如遭退選可於人工加退選期間補救。': {'en':'After the add/drop deadline, if there are still schedule conflicts or duplicate course codes, the Academic Affairs Division will forcibly drop all of them. Handle these yourself before the deadline; you can remedy via manual add/drop if dropped.','vi':'Sau thời hạn thêm/bỏ, nếu vẫn còn xung đột lịch hoặc mã khóa trùng, Phòng Học vụ sẽ bắt buộc bỏ tất cả. Hãy tự xử lý trước thời hạn; bạn có thể khắc phục qua thêm/bỏ thủ công nếu bị bỏ.','id':'Setelah batas waktu tambah/batal, jika masih ada bentrok atau kode duplikat, Divisi Akademik akan memaksa membatalkan semuanya. Tangani sendiri sebelum batas waktu; bisa diperbaiki melalui tambah/batal manual jika dibatalkan.','ms':'Selepas tarikh akhir tambah/tanggal, jika masih ada berlanggaran atau kod berganda, Bahagian Akademik akan memaksa tanggalkan semua. Tangani sendiri sebelum tarikh akhir; boleh dipulihkan melalui tambah/tanggal manual jika ditanggalkan.','th':'หลังจากกำหนดเวลาเพิ่ม/ถอน ถ้ายังมีการชนตารางหรือรหัสวิชาซ้ำ ฝ่ายวิชาการจะบังคับถอนทั้งหมด จัดการด้วยตนเองก่อนกำหนดเวลา สามารถแก้ไขผ่านการเพิ่ม/ถอนด้วยตนเองหากถูกถอน','ja':'加退選締切後も衝突や重複課番号があれば、課務組が全て強制退選します。締切前に自分で処理してください。退選になった場合は手動加退選期間に対処可能。','ko':'추가/취소 마감 후 시간표 충돌 또는 동일 과목 코드가 남아 있으면 교학처에서 모두 강제 취소합니다. 마감 전에 직접 처리하세요. 취소된 경우 수동 추가/취소 기간에 해결 가능합니다.','my':'ထည့်/ဖြုတ်သတ်မှတ်ရက်ပြီးနောက် အချိန်ဇယားထပ်ကိုင်မှု သို့မဟုတ် တူညီသောသင်တန်းကုဒ် ကျန်ရှိနေပါက ပညာရေးရေးရာဌာနမှ အတင်းဖြုတ်မည်ဖြစ်သည်'},
    '部份課程有群組上限：': {'en':'Some courses have group limits:','vi':'Một số khóa học có giới hạn nhóm:','id':'Beberapa mata kuliah memiliki batas kelompok:','ms':'Sesetengah kursus mempunyai had kumpulan:','th':'บางวิชามีขีดจำกัดกลุ่ม:','ja':'一部の科目にはグループ上限があります：','ko':'일부 과목에는 그룹 제한이 있습니다:','my':'အချို့သောသင်တန်းများတွင် အုပ်စုကန့်သတ်ချက်ရှိသည်:'},
    '如核心通識每學期最多選 2 門、體育課 1 門、大一英文 1 門等。選課前請確認課程群組規定。': {'en':'For example, Core General Education is limited to 2 per semester, PE 1 per semester, Freshman English 1 per semester, etc. Please check group restrictions before registering.','vi':'Ví dụ, Giáo dục đại cương cốt lõi tối đa 2 môn mỗi học kỳ, Thể dục 1 môn, Tiếng Anh năm nhất 1 môn. Vui lòng kiểm tra hạn chế nhóm trước khi đăng ký.','id':'Misalnya, Pendidikan Umum Inti dibatasi 2 per semester, Olahraga 1, Bahasa Inggris Tahun Pertama 1 dll. Periksa batasan kelompok sebelum mendaftar.','ms':'Contohnya, Pendidikan Umum Teras terhad 2 setiap semester, Pendidikan Jasmani 1, Bahasa Inggeris Tahun Pertama 1 dll. Sila semak had kumpulan sebelum mendaftar.','th':'เช่น วิชาการศึกษาทั่วไปหลัก สูงสุด 2 วิชาต่อภาคเรียน พลศึกษา 1 วิชา ภาษาอังกฤษปีหนึ่ง 1 วิชา เป็นต้น กรุณาตรวจสอบข้อจำกัดกลุ่มก่อนลงทะเบียน','ja':'例：核心教養は毎学期最大2科目、体育1科目、大学1年英語1科目など。登録前にグループ上限を確認してください。','ko':'예: 핵심 교양은 학기당 최대 2과목, 체육 1과목, 1학년 영어 1과목 등. 등록 전에 그룹 제한을 확인하세요.','my':'ဥပမာ: Core General Education တစ်နှစ်ဝက်လျှင် အများဆုံး ၂ ဘာသာ၊ ကိုယ်လက်ခန်သင်ကြားရေး ၁ ဘာသာ၊ ပထမနှစ် အင်္ဂလိပ်ဘာသာ ၁ ဘာသာ စသည်။ မှတ်ပုံတင်မတိုင်မီ အုပ်စုကန့်သတ်ချက်စစ်ဆေးပါ'},
    '學分費：': {'en':'Credit Fees:','vi':'Phí tín chỉ:','id':'Biaya SKS:','ms':'Yuran Kredit:','th':'ค่าธรรมเนียมหน่วยกิต:','ja':'学費（単位費用）：','ko':'학점 수수료:','my':'ခရက်ဒစ်ကြေး:'},
    '修 ≤ 9 學分按比例繳學分費與雜費；≥ 10 學分繳全額學費與雜費（師培課程學分另計）。': {'en':'≤ 9 credits: pay proportional credit fees and misc. fees; ≥ 10 credits: pay full tuition and misc. fees (teacher education credits counted separately).','vi':'≤ 9 tín chỉ: thanh toán phí tín chỉ tỷ lệ và phí phụ; ≥ 10 tín chỉ: thanh toán học phí đầy đủ và phí phụ (tín chỉ giáo dục giáo viên tính riêng).','id':'≤ 9 kredit: bayar biaya kredit proporsional dan biaya lain; ≥ 10 kredit: bayar penuh biaya kuliah dan biaya lain (kredit pendidikan guru dihitung terpisah).','ms':'≤ 9 kredit: bayar yuran kredit berkadar dan yuran lain; ≥ 10 kredit: bayar yuran pengajian penuh dan yuran lain (kredit pendidikan guru dikira berasingan).','th':'≤ 9 หน่วยกิต: ชำระค่าธรรมเนียมหน่วยกิตตามสัดส่วนและค่าใช้จ่ายอื่น ≥ 10 หน่วยกิต: ชำระค่าเล่าเรียนเต็มจำนวนและค่าใช้จ่ายอื่น (หน่วยกิตครูศึกษาคำนวณแยก)','ja':'≤9単位：比例按分で単位費用と雑費を納付；≥10単位：全額の授業料と雑費を納付（師範教育課程の単位は別途計算）。','ko':'≤ 9학점: 비례 학점 수수료 및 기타 비용 납부; ≥ 10학점: 전액 등록금 및 기타 비용 납부 (교직 학점은 별도 계산).','my':'≤ ၉ ခရက်ဒစ်: အချိုးကျ ခရက်ဒစ်ကြေးနှင့် အခြားကြေး ပေးချေပါ; ≥ ၁၀ ခရက်ဒစ်: ပြည့်ပြည့်ဝဝ ကျောင်းလခနှင့် အခြားကြေး ပေးချေပါ'},
    '學分抵免': {'en':'Credit Exemption','vi':'Miễn tín chỉ','id':'Pembebasan Kredit','ms':'Pengecualian Kredit','th':'การยกเว้นหน่วยกิต','ja':'単位免除','ko':'학점 면제','my':'ခရက်ဒစ်ကင်းလွတ်ခွင့်'},
    '學分抵免由註冊組負責辦理（非課務組），請至教務處註冊組查詢申請時間與規定。': {'en':'Credit exemption is handled by the Registration Section (not the Academic Affairs Division). Please contact the Registration Section of the Academic Office for application timing and regulations.','vi':'Miễn tín chỉ do Phòng Đăng ký phụ trách (không phải Phòng Học vụ). Vui lòng liên hệ Phòng Đăng ký của Văn phòng Học vụ để biết thời gian và quy định.','id':'Pembebasan kredit ditangani oleh Bagian Registrasi (bukan Divisi Akademik). Hubungi Bagian Registrasi Kantor Akademik untuk waktu dan peraturan pendaftaran.','ms':'Pengecualian kredit dikendalikan oleh Bahagian Pendaftaran (bukan Bahagian Akademik). Sila hubungi Bahagian Pendaftaran Pejabat Akademik untuk masa dan peraturan permohonan.','th':'การยกเว้นหน่วยกิตดูแลโดยส่วนลงทะเบียน (ไม่ใช่ฝ่ายวิชาการ) กรุณาติดต่อส่วนลงทะเบียนของสำนักงานวิชาการสำหรับเวลาและระเบียบการสมัคร','ja':'単位免除は登録課が担当（課務組ではありません）。申請時期や規定は教務処登録課にお問い合わせください。','ko':'학점 면제는 등록 부서(교학처가 아님)에서 담당합니다. 신청 시기 및 규정은 교학처 등록 부서에 문의하세요.','my':'ခရက်ဒစ်ကင်းလွတ်ခွင့်ကို မှတ်ပုံတင်ဌာနမှ ကိုင်တွယ်သည် (ပညာရေးရေးရာဌာနမဟုတ်)။ လျှောက်ထားသည့်အချိန်နှင့် စည်းမျဉ်းများအတွက် မှတ်ပုံတင်ဌာနသို့ ဆက်သွယ်ပါ'},
    '抵免結果公告後，若被抵免課程仍在選課清單中，請自行退選。轉學生需自行於加退選期間選課，系統不會代選任何課程。': {'en':'After exemption results are announced, if exempted courses are still on your registration list, please drop them yourself. Transfer students must register for courses themselves during the add/drop period; the system will not auto-select any courses.','vi':'Sau khi kết quả miễn được công bố, nếu các môn được miễn vẫn trong danh sách đăng ký, hãy tự bỏ. Sinh viên chuyển trường phải tự đăng ký trong giai đoạn thêm/bỏ; hệ thống không tự chọn.','id':'Setelah hasil pembebasan diumumkan, jika mata kuliah yang dibebaskan masih ada di daftar registrasimu, hapus sendiri. Mahasiswa pindahan harus mendaftar sendiri selama masa tambah/batal; sistem tidak otomatis memilih.','ms':'Selepas keputusan pengecualian diumumkan, jika kursus yang dikecualikan masih dalam senarai pendaftaran anda, sila tanggalkan sendiri. Pelajar pindahan mesti mendaftar sendiri semasa tempoh tambah/tanggal; sistem tidak akan memilih secara automatik.','th':'หลังจากประกาศผลการยกเว้น หากวิชาที่ยกเว้นยังอยู่ในรายการลงทะเบียน กรุณาถอนด้วยตนเอง นักศึกษาโอนย้ายต้องลงทะเบียนเองในช่วงเพิ่ม/ถอน ระบบจะไม่เลือกวิชาให้อัตโนมัติ','ja':'免除結果発表後、免除科目が履修リストに残っていれば自分で退選してください。転学生は加退選期間に自分で選課してください。システムは代わりに選択しません。','ko':'면제 결과 공지 후 면제된 과목이 여전히 수강신청 목록에 있으면 직접 취소하세요. 편입생은 추가/취소 기간에 직접 수강신청해야 합니다; 시스템이 자동으로 선택하지 않습니다.','my':'ကင်းလွတ်ခွင့်ရလဒ်ကြေညာပြီးနောက် ကင်းလွတ်ခွင့်ရသောသင်တန်းများ မှတ်ပုံတင်ရေးစာရင်းတွင် ကျန်ရှိနေပါက ကိုယ်တိုင်ဖြုတ်ပါ'},
    '課務組聯絡資訊': {'en':'Academic Affairs Division Contact Info','vi':'Thông tin liên hệ Phòng Học vụ','id':'Info Kontak Divisi Akademik','ms':'Maklumat Hubungan Bahagian Akademik','th':'ข้อมูลติดต่อฝ่ายวิชาการ','ja':'課務組連絡先情報','ko':'교학처 연락처 정보','my':'ပညာရေးရေးရာဌာန ဆက်သွယ်ရေးသတင်းအချက်အလက်'},
    '業務項目': {'en':'Service Area','vi':'Lĩnh vực dịch vụ','id':'Area Layanan','ms':'Kawasan Perkhidmatan','th':'ด้านบริการ','ja':'業務内容','ko':'업무 영역','my':'ဝန်ဆောင်မှုနယ်ပယ်'},
    '電話分機（03-4227151 +）': {'en':'Phone Extension (03-4227151 +)','vi':'Số nội bộ (03-4227151 +)','id':'Ext. Telepon (03-4227151 +)','ms':'Sambungan Telefon (03-4227151 +)','th':'ต่อโทรศัพท์ (03-4227151 +)','ja':'電話内線（03-4227151 +）','ko':'전화 내선 (03-4227151 +)','my':'ဖုန်းတိုး (03-4227151 +)'},
    '選課、課務相關': {'en':'Course Registration & Academic Affairs','vi':'Đăng ký & Học vụ','id':'Registrasi & Urusan Akademik','ms':'Pendaftaran & Hal Ehwal Akademik','th':'การลงทะเบียนและกิจการวิชาการ','ja':'選課・課務関連','ko':'수강신청 및 교학 관련','my':'မှတ်ပုံတင်ရေးနှင့် ပညာရေးရေးရာ'},
    '校際選課（本校至他校）': {'en':'Inter-School Registration (NCU to Other Schools)','vi':'Đăng ký liên trường (NCU sang trường khác)','id':'Registrasi Antar Kampus (NCU ke Kampus Lain)','ms':'Pendaftaran Antara Sekolah (NCU ke Sekolah Lain)','th':'การลงทะเบียนระหว่างมหาวิทยาลัย (NCU ไปมหาวิทยาลัยอื่น)','ja':'校際選課（本校から他校へ）','ko':'학교 간 수강신청 (NCU에서 타교로)','my':'ကျောင်းများကြား မှတ်ပုံတင်ရေး (NCU မှ အခြားကျောင်းများသို့)'},
    '校際選課（他校至中大）': {'en':'Inter-School Registration (Other Schools to NCU)','vi':'Đăng ký liên trường (Trường khác sang NCU)','id':'Registrasi Antar Kampus (Kampus Lain ke NCU)','ms':'Pendaftaran Antara Sekolah (Sekolah Lain ke NCU)','th':'การลงทะเบียนระหว่างมหาวิทยาลัย (มหาวิทยาลัยอื่นไป NCU)','ja':'校際選課（他校から本校へ）','ko':'학교 간 수강신청 (타교에서 NCU로)','my':'ကျောင်းများကြား မှတ်ပုံတင်ရေး (အခြားကျောင်းများမှ NCU သို့)'},
    '暑修': {'en':'Summer Session','vi':'Học hè','id':'Sesi Musim Panas','ms':'Sesi Musim Panas','th':'การเรียนภาคฤดูร้อน','ja':'夏期集中授業','ko':'여름 수업','my':'နွေရာသီသင်တန်း'},
    '數位學習平台': {'en':'Digital Learning Platform','vi':'Nền tảng học trực tuyến','id':'Platform Pembelajaran Digital','ms':'Platform Pembelajaran Digital','th':'แพลตฟอร์มการเรียนรู้ดิจิทัล','ja':'デジタル学習プラットフォーム','ko':'디지털 학습 플랫폼','my':'ဒစ်ဂျစ်တယ်သင်ယူမှုပလပ်ဖောင်း'},
    '導師輔導選課問題': {'en':'Advisor-Guided Course Selection Issues','vi':'Vấn đề chọn khóa học với cố vấn','id':'Masalah Pemilihan Mata Kuliah dengan Penasihat','ms':'Isu Pemilihan Kursus dengan Penasihat','th':'ปัญหาการเลือกวิชากับอาจารย์ที่ปรึกษา','ja':'指導教員による履修指導の問題','ko':'지도교수 상담 수강신청 문제','my':'ဆရာမှ လမ်းညွှန်သောသင်တန်းရွေးချယ်မှုပြဿနာများ'},
    '相關連結': {'en':'Related Links','vi':'Liên kết liên quan','id':'Tautan Terkait','ms':'Pautan Berkaitan','th':'ลิงก์ที่เกี่ยวข้อง','ja':'関連リンク','ko':'관련 링크','my':'ဆက်စပ်လင့်ခ်များ'},
    'NCU 選課系統 ↗': {'en':'NCU Course Registration System ↗','vi':'Hệ thống Đăng ký NCU ↗','id':'Sistem Registrasi NCU ↗','ms':'Sistem Pendaftaran NCU ↗','th':'ระบบลงทะเบียนวิชาเรียน NCU ↗','ja':'NCU履修登録システム ↗','ko':'NCU 수강신청 시스템 ↗','my':'NCU သင်တန်းမှတ်ပုံတင်ရေးစနစ် ↗'},
    '課務日程表 ↗': {'en':'Course Schedule Calendar ↗','vi':'Lịch học kỳ ↗','id':'Kalender Jadwal ↗','ms':'Kalendar Jadual ↗','th':'ตารางประจำภาคเรียน ↗','ja':'課務日程表 ↗','ko':'과목 일정 달력 ↗','my':'သင်တန်းအချိန်ဇယား ↗'},
    '選課相關資訊 PDF ↗': {'en':'Course Registration Info PDF ↗','vi':'PDF Thông tin Đăng ký ↗','id':'PDF Info Registrasi ↗','ms':'PDF Maklumat Pendaftaran ↗','th':'PDF ข้อมูลลงทะเบียน ↗','ja':'選課関連情報PDF ↗','ko':'수강신청 관련 정보 PDF ↗','my':'မှတ်ပုံတင်ရေးသတင်းအချက်အလက် PDF ↗'},
    '選課系統操作手冊（英）↗': {'en':'Course System User Manual (English) ↗','vi':'Hướng dẫn Sử dụng Hệ thống (Tiếng Anh) ↗','id':'Panduan Pengguna Sistem (Bahasa Inggris) ↗','ms':'Manual Pengguna Sistem (Bahasa Inggeris) ↗','th':'คู่มือการใช้งานระบบ (ภาษาอังกฤษ) ↗','ja':'選課システム操作マニュアル（英語）↗','ko':'수강신청 시스템 사용자 매뉴얼 (영어) ↗','my':'သင်တန်းစနစ် လက်စွဲစာအုပ် (အင်္ဂလိပ်) ↗'},
    '教務處官網 ↗': {'en':'Academic Office Website ↗','vi':'Trang web Văn phòng Học vụ ↗','id':'Situs Web Kantor Akademik ↗','ms':'Laman Web Pejabat Akademik ↗','th':'เว็บไซต์สำนักงานวิชาการ ↗','ja':'教務処公式サイト ↗','ko':'교학처 공식 홈페이지 ↗','my':'ပညာရေးရေးရာရုံး ဝဘ်ဆိုဒ် ↗'},
}

# Also add new strings from the template edits
new_strings = {
    'SPARC（計中）帳號': {
        'en':'SPARC (Computer Center) account','vi':'tài khoản SPARC (Trung tâm Máy tính)',
        'id':'akun SPARC (Pusat Komputer)','ms':'akaun SPARC (Pusat Komputer)',
        'th':'บัญชี SPARC (ศูนย์คอมพิวเตอร์)','ja':'SPARC（計算機センター）アカウント',
        'ko':'SPARC (컴퓨터 센터) 계정','my':'SPARC (ကွန်ပြူတာဌာန) အကောင့်',
    },
}
translations.update(new_strings)

for lang in ['en', 'vi', 'id', 'ms', 'th', 'ja', 'ko', 'my']:
    path = f'locale/{lang}/LC_MESSAGES/django.po'
    po = polib.pofile(path)
    entry_map = {e.msgid: e for e in po}
    updated = added = 0
    for msgid, trans in translations.items():
        if msgid in entry_map:
            if not entry_map[msgid].msgstr:
                entry_map[msgid].msgstr = trans[lang]
                updated += 1
        else:
            po.append(polib.POEntry(msgid=msgid, msgstr=trans[lang]))
            added += 1
    po.save(path)
    po.save_as_mofile(path.replace('.po', '.mo'))
    sys.stdout.buffer.write((f'{lang}: updated {updated}, added {added}\n').encode('utf-8'))

print('Done.')
