# -*- coding: utf-8 -*-
import polib, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

MSGIDS = [
    "在大陸、海外地區或港澳製作之文書，應經海基會、駐外館處或臺北經濟文化辦事處（香港、澳門）驗證。依規定繳附之文件為外文者，應經駐外館處驗證，並檢附經駐外館驗證或國內公證人認證之中譯本；預防接種證明為外文者，應至該管衛生所轉譯登錄。但依外國人才專法第二十四條準用同法第九條規定申請就業金卡者，免附。",
    "居留一定期間之計算方式：自定居申請日往前推算，在臺連續居留滿一年（一年內得出境三十日，出境次數不予限制）或連續居留滿二年且每年在臺居住二百七十日以上。",
    "經許可居留，在臺灣地區居留一定期間，仍具備原居留條件者（親屬關係因結婚或收養發生者，應存續三年以上。但婚姻關係存續期間已生產子女者，不在此限），得申請在臺灣地區定居。",
    "經中央目的事業主管機關核准來臺就學者畢業後（HF168），依第十六條第一項第八款規定經許可居留連續滿五年，每年在臺灣地區居住一百八十三日以上，且最近一年於臺灣地區平均每月收入達中央勞動主管機關公告基本工資二倍以上者，得申請在臺灣地區定居。",
    "臺灣地區居留證有效期間屆滿前三十日內，原申請居留原因仍繼續存在者，得申請延期，每次不得逾二年；學生申請畢業延期居留者，自畢業當日起算六個月，延期居留期間屆滿前，得再申請延期一次，總延期居留期間最長為一年。（應備文件：1.申請書、2.臺灣地區居留證、3.其他相關證明文件）",
    "依外國人才專法第二十四條規定經許可居留，原申請居留原因仍繼續存在者，得申請延期居留：1.準用同法第八條規定者：每次最長為五年。2.準用同法第五條至第七條、第九條及第十條規定者：每次最長為三年。",
    "港澳居民逾期居留未滿三十日，原申請居留原因仍繼續存在者，經依相關規定處罰、繳清罰鍰後，得向本署重新申請居留；港澳居民未於居留期間屆滿前經許可延期居留，且逾期居留三十日以上者，應繳清罰款，並申請出境證出境。",
]

TRANSLATIONS = {
    "en": [
        "Documents produced in mainland China, overseas areas, or Hong Kong and Macau must be authenticated by the Straits Exchange Foundation (SEF), overseas missions, or the Taipei Economic and Cultural Office (Hong Kong, Macau). Documents submitted in a foreign language must be authenticated by overseas missions and accompanied by a verified Chinese translation; vaccination certificates in a foreign language must be transcribed and registered at the competent health center. Applicants for an Employment Gold Card under Article 9 applied mutatis mutandis pursuant to Article 24 of the Act are exempt.",
        "Calculation of continuous residence period: counted backward from the date of application for household registration, the applicant must have resided continuously in Taiwan for one full year (permitted to depart for up to 30 days within the year, with no limit on the number of departures) or continuously for two full years with residence in Taiwan for at least 270 days each year.",
        "A person who has been permitted to reside in the Taiwan Area for a fixed period and still meets the original residence conditions (where the kinship relationship arose from marriage or adoption, it must have existed for at least three years; however, if a child was born during the marriage, this restriction does not apply) may apply for permanent residence in the Taiwan Area.",
        "A person approved to study in Taiwan by the central competent authority who has graduated (HF168), has been permitted to reside continuously in Taiwan for five full years pursuant to Article 16, Paragraph 1, Subparagraph 8, has resided in Taiwan for at least 183 days each year, and whose average monthly income in Taiwan over the most recent year is at least twice the basic wage announced by the central labor authority, may apply for permanent residence in the Taiwan Area.",
        "Within 30 days before the expiration of a Taiwan Area Resident Certificate, if the original grounds for residence still continue to exist, the holder may apply for an extension not exceeding two years per extension; for students applying for a post-graduation residence extension, the extension period runs six months from the date of graduation, with one additional extension permitted before the period expires, for a maximum total extension of one year. (Required documents: 1. Application form; 2. Taiwan Area Resident Certificate; 3. Other relevant supporting documents.)",
        "A person permitted to reside pursuant to Article 24 of the Act for the Recruitment and Employment of Foreign Professionals whose original grounds for residence still continue to exist may apply for a residence extension: 1. For those applying mutatis mutandis under Article 8 of the same Act: each extension may not exceed five years. 2. For those applying mutatis mutandis under Articles 5 through 7, 9, and 10 of the same Act: each extension may not exceed three years.",
        "A Hong Kong or Macau resident who has overstayed by less than 30 days and whose original grounds for residence still continue to exist may re-apply to the Agency for residence after being penalized in accordance with applicable regulations and paying the fine in full; a Hong Kong or Macau resident who was not granted a residence extension before expiry and has overstayed for 30 days or more must pay the fine in full and apply for an exit permit to depart.",
    ],
    "vi": [
        "Các văn bản lập tại Trung Quốc đại lục, khu vực nước ngoài hoặc Hồng Kông và Ma Cao phải được xác thực bởi Hội đồng Giao lưu Eo biển (SEF), cơ quan đại diện ở nước ngoài hoặc Văn phòng Kinh tế và Văn hóa Đài Bắc (Hồng Kông, Ma Cao). Văn bản bằng ngoại ngữ phải được xác thực và kèm bản dịch tiếng Trung đã được chứng nhận; chứng nhận tiêm chủng bằng ngoại ngữ phải được phiên dịch và đăng ký tại trung tâm y tế địa phương. Người xin Thẻ vàng việc làm theo Điều 9 áp dụng tương tự theo Điều 24 của Đạo luật được miễn.",
        "Cách tính thời gian cư trú liên tục: tính ngược từ ngày nộp đơn đăng ký hộ khẩu, người nộp đơn phải cư trú liên tục tại Đài Loan đủ một năm (được phép xuất cảnh tối đa 30 ngày trong năm, không giới hạn số lần) hoặc liên tục đủ hai năm với thời gian cư trú tại Đài Loan ít nhất 270 ngày mỗi năm.",
        "Người đã được phép cư trú tại vùng Đài Loan trong thời gian nhất định và vẫn đáp ứng điều kiện cư trú ban đầu (quan hệ thân tộc do hôn nhân hoặc nhận con nuôi phải tồn tại ít nhất ba năm; nếu có con sinh ra trong thời kỳ hôn nhân, điều kiện này không áp dụng) có thể nộp đơn định cư thường trú tại vùng Đài Loan.",
        "Người được cơ quan có thẩm quyền trung ương cho phép đến Đài Loan học tập và đã tốt nghiệp (HF168), được phép cư trú liên tục tại Đài Loan đủ năm năm theo Điều 16, Khoản 1, Điểm 8, cư trú tại Đài Loan ít nhất 183 ngày mỗi năm, và thu nhập bình quân tháng tại Đài Loan trong năm gần nhất ít nhất gấp đôi mức lương cơ bản do cơ quan lao động trung ương công bố, có thể nộp đơn định cư thường trú tại vùng Đài Loan.",
        "Trong vòng 30 ngày trước khi Giấy chứng nhận cư trú vùng Đài Loan hết hạn, nếu lý do cư trú ban đầu vẫn tiếp tục tồn tại, người giữ có thể xin gia hạn, mỗi lần không quá hai năm; sinh viên xin gia hạn cư trú sau tốt nghiệp được gia hạn sáu tháng từ ngày tốt nghiệp, có thể xin thêm một lần trước khi hết hạn, tổng thời gian gia hạn tối đa một năm. (Hồ sơ cần thiết: 1. Đơn đăng ký; 2. Giấy chứng nhận cư trú vùng Đài Loan; 3. Các tài liệu chứng minh liên quan khác.)",
        "Người được phép cư trú theo Điều 24 của Đạo luật về tuyển dụng chuyên gia nước ngoài và lý do cư trú ban đầu vẫn tiếp tục tồn tại có thể xin gia hạn cư trú: 1. Áp dụng tương tự Điều 8 cùng đạo luật: mỗi lần không quá năm năm. 2. Áp dụng tương tự Điều 5 đến 7, 9 và 10 cùng đạo luật: mỗi lần không quá ba năm.",
        "Cư dân Hồng Kông hoặc Ma Cao ở quá hạn dưới 30 ngày và lý do cư trú ban đầu vẫn tiếp tục tồn tại có thể nộp đơn lại lên Cơ quan để xin cư trú sau khi bị xử phạt và đóng đủ tiền phạt; cư dân Hồng Kông hoặc Ma Cao không được gia hạn cư trú trước khi hết hạn và ở quá hạn từ 30 ngày trở lên phải đóng đủ tiền phạt và xin giấy phép xuất cảnh để rời đi.",
    ],
    "id": [
        "Dokumen yang dibuat di Tiongkok daratan, kawasan luar negeri, atau Hong Kong dan Makau harus dilegalisasi oleh Yayasan Pertukaran Lintas Selat (SEF), perwakilan luar negeri, atau Kantor Ekonomi dan Kebudayaan Taipei (Hong Kong, Makau). Dokumen berbahasa asing harus dilegalisasi dan disertai terjemahan bahasa Mandarin yang telah diverifikasi; sertifikat vaksinasi berbahasa asing harus diterjemahkan dan didaftarkan di puskesmas setempat. Pemohon Kartu Emas Kerja berdasarkan Pasal 9 yang diterapkan secara mutatis mutandis sesuai Pasal 24 Undang-Undang dikecualikan.",
        "Cara penghitungan jangka waktu tinggal berkesinambungan: dihitung mundur dari tanggal permohonan pendaftaran kependudukan, pemohon harus telah tinggal secara berkesinambungan di Taiwan selama satu tahun penuh (diizinkan keluar hingga 30 hari dalam setahun, tanpa batasan jumlah perjalanan) atau berkesinambungan selama dua tahun penuh dengan tinggal di Taiwan minimal 270 hari setiap tahun.",
        "Orang yang telah diizinkan tinggal di Wilayah Taiwan untuk jangka waktu tertentu dan masih memenuhi kondisi tinggal awal (hubungan kekeluargaan yang timbul dari pernikahan atau adopsi harus telah ada minimal tiga tahun; jika lahir anak selama pernikahan, ketentuan ini tidak berlaku) dapat mengajukan permohonan menetap permanen di Wilayah Taiwan.",
        "Orang yang diizinkan belajar ke Taiwan oleh otoritas pusat yang berwenang dan telah lulus (HF168), yang telah diizinkan tinggal berkesinambungan di Taiwan selama lima tahun penuh berdasarkan Pasal 16, Ayat 1, Butir 8, dengan tinggal di Taiwan minimal 183 hari setiap tahun dan penghasilan bulanan rata-rata di Taiwan dalam tahun terakhir mencapai minimal dua kali upah minimum yang diumumkan oleh otoritas ketenagakerjaan pusat, dapat mengajukan permohonan menetap permanen di Wilayah Taiwan.",
        "Dalam 30 hari sebelum Surat Izin Tinggal Wilayah Taiwan berakhir, jika alasan tinggal awal masih terus ada, pemegang dapat mengajukan perpanjangan, tidak boleh melebihi dua tahun per perpanjangan; bagi mahasiswa yang mengajukan perpanjangan tinggal pascalulus, masa perpanjangan enam bulan sejak tanggal kelulusan, satu kali perpanjangan lanjutan dapat diajukan sebelum masa berakhir, total masa perpanjangan maksimal satu tahun. (Dokumen yang diperlukan: 1. Formulir permohonan; 2. Surat Izin Tinggal Wilayah Taiwan; 3. Dokumen pendukung terkait lainnya.)",
        "Orang yang telah diizinkan tinggal berdasarkan Pasal 24 Undang-Undang Rekrutmen dan Ketenagakerjaan Tenaga Profesional Asing dan alasan tinggal awal masih terus ada dapat mengajukan perpanjangan tinggal: 1. Berdasarkan Pasal 8 yang diterapkan secara mutatis mutandis: setiap perpanjangan tidak boleh melebihi lima tahun. 2. Berdasarkan Pasal 5 hingga 7, 9, dan 10 yang diterapkan secara mutatis mutandis: setiap perpanjangan tidak boleh melebihi tiga tahun.",
        "Warga Hong Kong atau Makau yang tinggal melebihi masa izin kurang dari 30 hari dan alasan tinggal awal masih terus ada dapat mengajukan kembali permohonan tinggal ke Badan setelah dikenai sanksi dan melunasi denda; warga Hong Kong atau Makau yang tidak mendapat perpanjangan tinggal sebelum masa berakhir dan telah melampaui masa izin 30 hari atau lebih harus melunasi denda dan mengajukan izin keluar untuk meninggalkan Taiwan.",
    ],
    "ms": [
        "Dokumen yang disediakan di China daratan, kawasan luar negara, atau Hong Kong dan Macao mesti disahkan oleh Yayasan Pertukaran Selat (SEF), misi luar negara, atau Pejabat Ekonomi dan Kebudayaan Taipei (Hong Kong, Macao). Dokumen dalam bahasa asing mesti disahkan dan disertai terjemahan bahasa Cina yang telah disahkan; sijil vaksinasi dalam bahasa asing mesti diterjemahkan dan didaftarkan di pusat kesihatan berkenaan. Pemohon Kad Emas Pekerjaan di bawah Perkara 9 yang dipakai secara mutatis mutandis mengikut Perkara 24 Akta dikecualikan.",
        "Cara pengiraan tempoh bermastautin berterusan: dikira mundur dari tarikh permohonan pendaftaran isi rumah, pemohon mesti telah bermastautin secara berterusan di Taiwan selama satu tahun penuh (dibenarkan keluar sehingga 30 hari dalam setahun, tanpa had bilangan perjalanan) atau secara berterusan selama dua tahun penuh dengan bermastautin di Taiwan sekurang-kurangnya 270 hari setiap tahun.",
        "Seseorang yang telah dibenarkan bermastautin di Kawasan Taiwan untuk tempoh tertentu dan masih memenuhi syarat bermastautin asal (hubungan kekeluargaan yang timbul daripada perkahwinan atau pengambilan anak angkat mesti telah wujud sekurang-kurangnya tiga tahun; jika anak dilahirkan semasa perkahwinan, sekatan ini tidak terpakai) boleh memohon bermastautin tetap di Kawasan Taiwan.",
        "Seseorang yang diluluskan belajar ke Taiwan oleh pihak berkuasa pusat yang berkenaan dan telah menamatkan pengajian (HF168), yang telah dibenarkan bermastautin secara berterusan di Taiwan selama lima tahun penuh mengikut Perkara 16, Perenggan 1, Subperenggan 8, dengan bermastautin di Taiwan sekurang-kurangnya 183 hari setiap tahun dan purata pendapatan bulanan di Taiwan dalam tahun terkini sekurang-kurangnya dua kali gaji minimum yang diumumkan oleh pihak berkuasa buruh pusat, boleh memohon bermastautin tetap di Kawasan Taiwan.",
        "Dalam tempoh 30 hari sebelum Permit Bermastautin Kawasan Taiwan tamat tempoh, jika sebab bermastautin asal masih berterusan, pemegang boleh memohon perpanjangan, tidak melebihi dua tahun setiap perpanjangan; pelajar yang memohon perpanjangan bermastautin selepas tamat pengajian mendapat enam bulan dari tarikh tamat pengajian, satu perpanjangan lanjutan boleh dimohon sebelum tempoh tamat, jumlah tempoh perpanjangan maksimum satu tahun. (Dokumen yang diperlukan: 1. Borang permohonan; 2. Permit Bermastautin Kawasan Taiwan; 3. Dokumen sokongan berkaitan lain.)",
        "Seseorang yang telah dibenarkan bermastautin mengikut Perkara 24 Akta Pengambilan dan Pekerjaan Profesional Asing dan sebab bermastautin asal masih berterusan boleh memohon perpanjangan bermastautin: 1. Memohon secara mutatis mutandis di bawah Perkara 8 akta yang sama: setiap perpanjangan tidak melebihi lima tahun. 2. Memohon secara mutatis mutandis di bawah Perkara 5 hingga 7, 9 dan 10 akta yang sama: setiap perpanjangan tidak melebihi tiga tahun.",
        "Pemastautin Hong Kong atau Macao yang bermastautin melebihi had kurang daripada 30 hari dan sebab bermastautin asal masih berterusan boleh memohon semula kepada Agensi untuk bermastautin selepas dikenakan penalti dan membayar denda sepenuhnya; pemastautin Hong Kong atau Macao yang tidak mendapat perpanjangan bermastautin sebelum tamat tempoh dan telah bermastautin melebihi had 30 hari atau lebih mesti membayar denda sepenuhnya dan memohon permit keluar untuk meninggalkan Taiwan.",
    ],
    "th": [
        "เอกสารที่จัดทำในจีนแผ่นดินใหญ่ พื้นที่ต่างประเทศ หรือฮ่องกงและมาเก๊า ต้องได้รับการรับรองจากมูลนิธิแลกเปลี่ยนช่องแคบ (SEF) สำนักงานผู้แทนต่างประเทศ หรือสำนักงานเศรษฐกิจและวัฒนธรรมไทเป (ฮ่องกง มาเก๊า) เอกสารภาษาต่างประเทศต้องได้รับการรับรองและแนบคำแปลภาษาจีนที่ผ่านการรับรอง ใบรับรองการฉีดวัคซีนภาษาต่างประเทศต้องแปลและลงทะเบียนที่ศูนย์อนามัย ผู้สมัครบัตรทองการจ้างงานตามมาตรา 9 ที่ใช้บังคับโดยอนุโลมตามมาตรา 24 แห่งพระราชบัญญัติได้รับการยกเว้น",
        "วิธีการคำนวณระยะเวลาพำนักต่อเนื่อง: นับย้อนหลังจากวันที่ยื่นขอทะเบียนบ้าน ผู้สมัครต้องพำนักต่อเนื่องในไต้หวันครบหนึ่งปี (อนุญาตให้ออกนอกประเทศได้สูงสุด 30 วันต่อปี ไม่จำกัดจำนวนครั้ง) หรือพำนักต่อเนื่องครบสองปีโดยพำนักในไต้หวันอย่างน้อย 270 วันต่อปี",
        "บุคคลที่ได้รับอนุญาตให้พำนักในเขตไต้หวันเป็นระยะเวลาหนึ่งและยังคงมีคุณสมบัติตามเงื่อนไขการพำนักเดิม (ความสัมพันธ์ทางครอบครัวที่เกิดจากการสมรสหรือการรับบุตรบุญธรรมต้องมีระยะเวลาอย่างน้อยสามปี อย่างไรก็ตาม หากมีบุตรเกิดขึ้นในช่วงสมรส ข้อจำกัดนี้ไม่ใช้บังคับ) สามารถยื่นขอพำนักถาวรในเขตไต้หวันได้",
        "บุคคลที่ได้รับอนุมัติจากหน่วยงานกลางที่มีอำนาจให้มาศึกษาในไต้หวันและสำเร็จการศึกษาแล้ว (HF168) ซึ่งได้รับอนุญาตให้พำนักต่อเนื่องในไต้หวันครบห้าปีตามมาตรา 16 วรรค 1 อนุมาตรา 8 พำนักในไต้หวันอย่างน้อย 183 วันต่อปี และรายได้เฉลี่ยต่อเดือนในไต้หวันในปีล่าสุดอย่างน้อยสองเท่าของค่าแรงขั้นต่ำที่หน่วยงานแรงงานกลางประกาศ สามารถยื่นขอพำนักถาวรในเขตไต้หวันได้",
        "ภายใน 30 วันก่อนที่ใบอนุญาตถิ่นที่อยู่เขตไต้หวันจะหมดอายุ หากเหตุผลการพำนักเดิมยังคงมีอยู่ต่อเนื่อง ผู้ถือสามารถยื่นขอต่ออายุได้ แต่ละครั้งไม่เกินสองปี นักศึกษาที่ยื่นขอต่ออายุการพำนักหลังสำเร็จการศึกษาจะได้รับระยะเวลาหกเดือนจากวันสำเร็จการศึกษา โดยสามารถยื่นขอต่ออายุเพิ่มเติมได้อีกหนึ่งครั้งก่อนหมดอายุ รวมสูงสุดหนึ่งปี (เอกสารที่ต้องใช้: 1. แบบฟอร์มใบสมัคร 2. ใบอนุญาตถิ่นที่อยู่เขตไต้หวัน 3. เอกสารหลักฐานที่เกี่ยวข้องอื่นๆ)",
        "บุคคลที่ได้รับอนุญาตให้พำนักตามมาตรา 24 แห่งพระราชบัญญัติการสรรหาและจ้างงานผู้เชี่ยวชาญต่างชาติและเหตุผลการพำนักเดิมยังคงมีอยู่ต่อเนื่อง สามารถยื่นขอต่ออายุการพำนักได้: 1. ผู้ที่ยื่นขอโดยอนุโลมตามมาตรา 8 แห่งกฎหมายฉบับเดียวกัน: แต่ละครั้งไม่เกินห้าปี 2. ผู้ที่ยื่นขอโดยอนุโลมตามมาตรา 5 ถึง 7, 9 และ 10 แห่งกฎหมายฉบับเดียวกัน: แต่ละครั้งไม่เกินสามปี",
        "ผู้อยู่อาศัยในฮ่องกงหรือมาเก๊าที่พำนักเกินกำหนดน้อยกว่า 30 วันและเหตุผลการพำนักเดิมยังคงมีอยู่ต่อเนื่อง สามารถยื่นขอพำนักใหม่ต่อสำนักงานได้หลังจากถูกลงโทษตามกฎระเบียบที่เกี่ยวข้องและชำระค่าปรับครบถ้วน ผู้อยู่อาศัยในฮ่องกงหรือมาเก๊าที่ไม่ได้รับการต่ออายุการพำนักก่อนหมดอายุและพำนักเกินกำหนด 30 วันขึ้นไป ต้องชำระค่าปรับครบถ้วนและยื่นขอใบอนุญาตออกนอกประเทศเพื่อออกเดินทาง",
    ],
    "ko": [
        "중국 대륙, 해외 지역 또는 홍콩·마카오에서 작성된 문서는 해협교류기금회(SEF), 해외 주재 기관 또는 타이베이 경제문화판사처(홍콩·마카오)의 인증을 받아야 합니다. 외국어로 제출된 문서는 해외 주재 기관의 인증과 함께 인증된 중국어 번역본을 첨부해야 합니다. 외국어로 된 예방접종 증명서는 관할 보건소에서 번역 등록해야 합니다. 단, 해당 법률 제24조를 준용하여 제9조에 따라 취업골드카드를 신청하는 자는 면제됩니다.",
        "일정 기간 거류 계산 방법: 호적 신청일로부터 역산하여 대만에 1년 연속 거류（1년 이내 출국 30일 허용, 출국 횟수 제한 없음）또는 연속 2년 거류하면서 매년 대만에 270일 이상 거주해야 합니다.",
        "일정 기간 거류를 허가받고 대만 지역에 거류하면서 원래의 거류 조건을 갖추고 있는 자（혼인 또는 입양으로 발생한 친족 관계는 3년 이상 존속해야 하며, 혼인 기간 중 자녀를 출산한 경우에는 적용하지 않음）는 대만 지역 정주를 신청할 수 있습니다.",
        "중앙 목적사업 주관기관의 허가를 받아 대만에 유학한 후 졸업한 자（HF168）로서, 제16조 제1항 제8호에 따라 허가된 거류가 연속 5년 이상이고, 매년 대만 지역에 183일 이상 거주하며, 최근 1년간 대만 지역의 평균 월 수입이 중앙 노동 주관기관이 공고한 최저임금의 2배 이상인 자는 대만 지역 정주를 신청할 수 있습니다.",
        "대만 지역 거류증 유효기간 만료 30일 이내에 원래의 거류 신청 사유가 계속 존재하는 경우, 연장을 신청할 수 있으며 매회 2년을 초과할 수 없습니다. 졸업 후 거류 연장을 신청하는 학생은 졸업일로부터 6개월이 연장 기간이며, 연장 기간 만료 전 추가 연장 신청을 1회 할 수 있고, 총 연장 거류 기간은 최장 1년입니다.（구비서류: 1. 신청서, 2. 대만 지역 거류증, 3. 기타 관련 증명서류）",
        "외국인 인재 특별법 제24조 규정에 따라 거류를 허가받은 자로서 원래의 거류 신청 사유가 계속 존재하는 경우 거류 연장을 신청할 수 있습니다: 1. 동법 제8조를 준용하여 신청하는 경우: 매회 최장 5년. 2. 동법 제5조부터 제7조, 제9조 및 제10조를 준용하여 신청하는 경우: 매회 최장 3년.",
        "홍콩·마카오 거주자로서 30일 미만 초과 거류하고 원래의 거류 신청 사유가 계속 존재하는 경우, 관련 규정에 따라 처벌을 받고 벌금을 납부한 후 당 기관에 거류를 재신청할 수 있습니다. 거류 기간 만료 전에 연장 거류 허가를 받지 못한 채 30일 이상 초과 거류한 홍콩·마카오 거주자는 벌금을 납부하고 출경증을 신청하여 출국해야 합니다.",
    ],
    "my": [
        "တရုတ်ပြည်မကြီး၊ နိုင်ငံရပ်ခြားနယ်မြေများ သို့မဟုတ် ဟောင်ကောင်နှင့် မကာအိုတွင် ပြုလုပ်သောစာချုပ်စာတမ်းများကို ချောင်းကြားဖလှယ်ရေးဖောင်ဒေးရှင်း (SEF)၊ နိုင်ငံရပ်ခြားကိုယ်စားလှယ်ရုံးများ သို့မဟုတ် ထိုင်ပေ စီးပွားရေးနှင့် ယဉ်ကျေးမှုရုံး (ဟောင်ကောင်၊ မကာအို) မှ အတည်ပြုရမည်။ နိုင်ငံရပ်ခြားဘာသာဖြင့် တင်ပြသောစာရွက်စာတမ်းများကို အတည်ပြုပြီး အတည်ပြုချက်ရ တရုတ်ဘာသာပြန်ချက်ကို ပူးတွဲတင်ပြရမည်။ နိုင်ငံရပ်ခြားဘာသာဖြင့် ရေးသားသောကာကွယ်ဆေးထိုးမှတ်တမ်းကို ဆိုင်ရာကျန်းမာရေးစင်တာတွင် ဘာသာပြန်ကာ မှတ်ပုံတင်ရမည်။ ပုဒ်မ ၂၄ ကို ပုဒ်မ ၉ ဖြင့် ချိတ်ဆက်ကျင့်သုံး၍ အလုပ်အကိုင် ရွှေကဒ်လျှောက်ထားသူများကို ကင်းလွတ်ခွင့်ပြုသည်။",
        "နေထိုင်မှုကာလ တွက်ချက်နည်း: အိမ်ထောင်မှုမှတ်ပုံတင် လျှောက်ထားသောနေ့မှ နောက်ပြန်တွက်ကာ လျှောက်ထားသူသည် တိုင်ဝမ်တွင် ဆက်တိုက် တစ်နှစ်ပြည့်နေထိုင်ရမည် (တစ်နှစ်အတွင်း ၃၀ ရက်အထိ ထွက်ခွာခွင့်ရှိ၍ ထွက်ခွာမှုအကြိမ်ရေ အကန့်အသတ်မရှိ) သို့မဟုတ် ဆက်တိုက် နှစ်နှစ်ပြည့်နေထိုင်ရမည်ဖြစ်ပြီး နှစ်တစ်နှစ်စီတွင် တိုင်ဝမ်တွင် အနည်းဆုံး ၂၇၀ ရက် နေထိုင်ရမည်။",
        "တိုင်ဝမ်နယ်မြေတွင် သတ်မှတ်ကာလ နေထိုင်ခွင့်ရပြီး မူလနေထိုင်ခွင့်အခြေအနေများ ဆက်ရှိနေသူ (မိသားစုဆက်ဆံရေး မင်္ဂလာဆောင်ခြင်း သို့မဟုတ် မွေးစားခြင်းကြောင့် ဖြစ်ပေါ်ခဲ့ပါက အနည်းဆုံး သုံးနှစ် ကြာမြင့်ရမည်; မင်္ဂလာဆောင်နေစဉ်အတွင်း ကလေးမွေးဖွားပါက ဤကန့်သတ်ချက် မသက်ရောက်) တိုင်ဝမ်နယ်မြေတွင် အမြဲတမ်းနေထိုင်ရန် လျှောက်ထားနိုင်သည်။",
        "မဟာဌာနဆိုင်ရာ ဗဟိုအာဏာပိုင်ဌာနမှ ခွင့်ပြုကာ တိုင်ဝမ်သို့ ပညာသင်ဆင်းပြီး ဘွဲ့ရပြီးသောသူ (HF168) ဖြစ်ပြီး ပုဒ်မ ၁၆၊ အပိုဒ်ခွဲ ၁၊ ပုဒ်မခွဲ ၈ အရ ဆက်တိုက် ငါးနှစ်ပြည့် နေထိုင်ခွင့်ရကာ နှစ်တစ်နှစ်စီတွင် တိုင်ဝမ်တွင် အနည်းဆုံး ၁၈၃ ရက် နေထိုင်ပြီး မကြာသေးမီနှစ်တစ်နှစ်အတွင်း တိုင်ဝမ်တွင် ပျမ်းမျှ လစဥ်ဝင်ငွေသည် ဗဟိုလုပ်သားဌာနမှ ကြေညာသော အနိမ့်ဆုံးလစာ၏ နှစ်ဆ ရောက်ရှိပါက တိုင်ဝမ်နယ်မြေတွင် အမြဲတမ်းနေထိုင်ရန် လျှောက်ထားနိုင်သည်။",
        "တိုင်ဝမ်နယ်မြေ နေထိုင်ခွင့်ကတ် သက်တမ်းကုန်ဆုံးရန် ၃၀ ရက်မတိုင်မီ မူလ နေထိုင်ခွင့်အကြောင်းပြချက် ဆက်ရှိနေပါက တိုးမြှင့်လျှောက်ထားနိုင်ပြီး တစ်ကြိမ်လျှင် နှစ်နှစ်မကျော်ရ။ ဘွဲ့ရပြီး နေထိုင်ခွင့်တိုးမြှင့်လျှောက်ထားသော ကျောင်းသားများအတွက် ဘွဲ့ရသောနေ့မှ ခြောက်လကာလ ဖြစ်ပြီး ထိုကာလမကုန်မီ နောက်ထပ်တိုးမြှင့်ခွင့် တစ်ကြိမ်ပြုနိုင်ကာ ကာလ စုစုပေါင်း အများဆုံး တစ်နှစ်ဖြစ်သည်။ (လိုအပ်သောစာရွက်စာတမ်းများ: ၁. လျှောက်လွှာ; ၂. တိုင်ဝမ်နယ်မြေ နေထိုင်ခွင့်ကတ်; ၃. သက်ဆိုင်ရာ အထောက်အထားစာရွက်စာတမ်းများ)",
        "နိုင်ငံခြားပညာရှင် ငှားရမ်းနိုင်ရေးဥပဒေ ပုဒ်မ ၂၄ အရ နေထိုင်ခွင့်ရပြီး မူလ နေထိုင်ခွင့်အကြောင်းပြချက် ဆက်ရှိနေသူသည် နေထိုင်ခွင့်တိုးမြှင့်ရန် လျှောက်ထားနိုင်သည်: ၁. ထိုဥပဒေ ပုဒ်မ ၈ ကို ချိတ်ဆက်ကျင့်သုံး၍ လျှောက်ထားသူ: တစ်ကြိမ်လျှင် အများဆုံး ငါးနှစ်။ ၂. ထိုဥပဒေ ပုဒ်မ ၅ မှ ၇၊ ပုဒ်မ ၉ နှင့် ၁၀ ကို ချိတ်ဆက်ကျင့်သုံး၍ လျှောက်ထားသူ: တစ်ကြိမ်လျှင် အများဆုံး သုံးနှစ်။",
        "ဟောင်ကောင် သို့မဟုတ် မကာအိုနေထိုင်သူ ၃၀ ရက်မပြည့်ဘဲ ကာလကျော်နေထိုင်ပြီး မူလ နေထိုင်ခွင့်အကြောင်းပြချက် ဆက်ရှိနေပါက ဆိုင်ရာနည်းဥပဒေများနှင့်အညီ အရေးယူမှုခံပြီး ဒဏ်ကြေးပေးဆပ်ပြီးနောက် ဌာနသို့ နေထိုင်ခွင့် ပြန်လည်လျှောက်ထားနိုင်သည်။ နေထိုင်ခွင့်ကာလ ကုန်ဆုံးမတိုင်မီ တိုးမြှင့်ခွင့်မရဘဲ ၃၀ ရက်နှင့်အထက် ကာလကျော်နေထိုင်သော ဟောင်ကောင် သို့မဟုတ် မကာအိုနေထိုင်သူများသည် ဒဏ်ကြေးပြည့်ဝပေးဆပ်ကာ ထွက်ခွာရေးဗီဇာ လျှောက်ထားပြီး ထွက်ခွာရမည်။",
    ],
}

langs = ['en', 'vi', 'id', 'ms', 'th', 'ko', 'my']
for lang in langs:
    path = 'locale/{}/LC_MESSAGES/django.po'.format(lang)
    po = polib.pofile(path)
    em = {e.msgid: e for e in po}
    added = 0
    for i, msgid in enumerate(MSGIDS):
        msgstr = TRANSLATIONS[lang][i]
        if msgid in em:
            if not em[msgid].msgstr.strip():
                em[msgid].msgstr = msgstr
                added += 1
        else:
            entry = polib.POEntry(msgid=msgid, msgstr=msgstr)
            po.append(entry)
            added += 1
    po.save(path)
    po.save_as_mofile(path.replace('.po', '.mo'))
    print('{}: added/updated {} entries, compiled OK'.format(lang, added))
