# Generated by Django 5.2.13 on 2026-04-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任務名稱')),
                ('description', models.TextField(blank=True, verbose_name='任務說明')),
                ('category', models.CharField(choices=[('visa', '簽證辦理'), ('enrollment', '入學手續'), ('housing', '住宿安排'), ('health', '健保醫療'), ('finance', '財務銀行'), ('language', '語言學習'), ('culture', '生活適應'), ('other', '其他事項')], default='other', max_length=20, verbose_name='分類')),
                ('identity_types', models.JSONField(blank=True, default=list, help_text='空列表 = 所有身份別', verbose_name='適用身份別')),
                ('admission_statuses', models.JSONField(blank=True, default=list, help_text='空列表 = 所有入學狀態', verbose_name='適用入學狀態')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_required', models.BooleanField(default=True, verbose_name='必要任務')),
                ('days_offset', models.IntegerField(blank=True, help_text='相對於預計抵台日期；負數=抵台前，正數=抵台後，空=無截止日', null=True, verbose_name='截止日偏移（天）')),
                ('reference_url', models.URLField(blank=True, verbose_name='參考連結')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '任務模板',
                'verbose_name_plural': '任務模板',
                'db_table': 'flow_steptemplate',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(max_length=30, verbose_name='身份別（快照）')),
                ('admission_status', models.CharField(max_length=20, verbose_name='入學狀態（快照）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_flow', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '個人化流程',
                'verbose_name_plural': '個人化流程',
                'db_table': 'flow_processflow',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任務名稱')),
                ('description', models.TextField(blank=True, verbose_name='任務說明')),
                ('category', models.CharField(choices=[('visa', '簽證辦理'), ('enrollment', '入學手續'), ('housing', '住宿安排'), ('health', '健保醫療'), ('finance', '財務銀行'), ('language', '語言學習'), ('culture', '生活適應'), ('other', '其他事項')], default='other', max_length=20, verbose_name='分類')),
                ('status', models.CharField(choices=[('todo', '待辦'), ('in_progress', '進行中'), ('done', '已完成')], default='todo', max_length=20, verbose_name='狀態')),
                ('is_required', models.BooleanField(default=True, verbose_name='必要任務')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('process_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flow.processflow', verbose_name='所屬流程')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.flowsteptemplate', verbose_name='來源模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者任務',
                'verbose_name_plural': '使用者任務',
                'db_table': 'flow_usertask',
                'ordering': ['order', 'due_date'],
            },
        ),
    ]
