# Generated by Django 6.0.4 on 2026-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否釘選'),
        ),
    ]
