# Generated by Django 6.0.4 on 2026-04-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chatbot_uploads/%Y/%m/%d/', verbose_name='附件檔案')),
                ('attachment_type', models.CharField(choices=[('file', '檔案'), ('image', '圖片'), ('camera', '拍照')], default='file', max_length=20, verbose_name='附件類型')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始檔名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chatbot.chatmessage', verbose_name='所屬訊息')),
            ],
            options={
                'verbose_name': '聊天附件',
                'verbose_name_plural': '聊天附件',
                'db_table': 'chatbot_attachment',
            },
        ),
    ]
