# Generated by Django 6.0.4 on 2026-05-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatknowledge_ko'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-is_pinned', '-updated_at'], 'verbose_name': '聊天對話', 'verbose_name_plural': '聊天對話'},
        ),
    ]
