# Generated by Django 6.0.4 on 2026-05-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chatsession_options'),
        ('chatbot', '0006_alter_chatsession_options'),
    ]

    operations = [
    ]
