# Generated by Django 6.0.4 on 2026-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_add_vi_columns_to_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatknowledge',
            name='content_vi',
            field=models.TextField(blank=True, verbose_name='越南文內容'),
        ),
        migrations.AlterField(
            model_name='chatknowledge',
            name='title_vi',
            field=models.CharField(blank=True, max_length=200, verbose_name='越南文標題'),
        ),
    ]
