# Generated by Django 6.0.4 on 2026-05-20 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_chatknowledge_content_vi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatknowledge',
            name='bot_type',
            field=models.CharField(choices=[('helper', 'StudyGo AI 小幫手'), ('friend', 'StudyGo AI 聊天好朋友'), ('both', '兩者都可使用')], default='helper', max_length=20, verbose_name='適用 AI'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='ai_mode',
            field=models.CharField(choices=[('helper', 'StudyGo AI 小幫手'), ('friend', 'StudyGo AI 聊天好朋友')], default='helper', max_length=20, verbose_name='AI 模式'),
        ),
        migrations.AlterField(
            model_name='chatknowledge',
            name='content_vi',
            field=models.TextField(blank=True, verbose_name='越文內容'),
        ),
        migrations.AlterField(
            model_name='chatknowledge',
            name='title_vi',
            field=models.CharField(blank=True, max_length=200, verbose_name='越文標題'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='新的聊天', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
