# Generated by Django 4.2.30 on 2026-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatknowledge_bot_type_chatsession_ai_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatknowledge',
            name='bot_type',
            field=models.CharField(choices=[('helper', 'StudyGo AI 小幫手'), ('friend', 'StudyGo AI 聊天好朋友'), ('both', '兩者都可使用')], default='helper', max_length=20, verbose_name='適用 AI'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_mode',
            field=models.CharField(choices=[('helper', 'StudyGo AI 小幫手'), ('friend', 'StudyGo AI 聊天好朋友')], default='helper', max_length=20, verbose_name='AI 模式'),
        ),
    ]
