# Generated by Django 6.0.4 on 2026-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_chatknowledge_bot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatknowledge',
            name='last_verified_at',
            field=models.DateField(blank=True, help_text='管理員最後一次確認此內容仍正確的日期', null=True, verbose_name='最後查核日期'),
        ),
        migrations.AddField(
            model_name='chatknowledge',
            name='source_url',
            field=models.URLField(blank=True, help_text='此知識的官方出處（移民署 / 學校公告等），會附在 AI 回答後供學生查證', verbose_name='官方來源連結'),
        ),
        migrations.AlterField(
            model_name='chatknowledge',
            name='bot_type',
            field=models.CharField(choices=[('helper', 'ReadyTo 任務小幫手'), ('friend', 'ReadyTo 聊天好朋友'), ('both', '兩者都可使用')], default='helper', max_length=20, verbose_name='適用 AI'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_mode',
            field=models.CharField(choices=[('helper', 'ReadyTo 任務小幫手'), ('friend', 'ReadyTo 聊天好朋友')], default='helper', max_length=20, verbose_name='AI 模式'),
        ),
    ]
