# Generated by Django 6.0.4 on 2026-07-08 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_chatknowledge_last_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', '👍 有幫助'), ('down', '👎 沒幫助')], max_length=10, verbose_name='評價')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatmessage', verbose_name='被評價的訊息')),
            ],
            options={
                'verbose_name': 'AI 回覆評價',
                'verbose_name_plural': 'AI 回覆評價',
                'db_table': 'chatbot_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
