# Generated by Django 6.0.4 on 2026-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_chatattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatknowledge',
            name='country',
            field=models.CharField(blank=True, choices=[('Japan', '日本'), ('Korea', '韓國'), ('Macau', '澳門'), ('Hong Kong', '香港'), ('Mongolia', '蒙古'), ('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Singapore', '新加坡'), ('India', '印度'), ('Pakistan', '巴基斯坦'), ('Bangladesh', '孟加拉'), ('Saudi Arabia', '沙烏地阿拉伯'), ('UAE', '阿拉伯聯合大公國'), ('Turkey', '土耳其'), ('UK', '英國'), ('France', '法國'), ('Germany', '德國'), ('Italy', '義大利'), ('Spain', '西班牙'), ('USA', '美國'), ('Canada', '加拿大'), ('Brazil', '巴西'), ('Mexico', '墨西哥'), ('Argentina', '阿根廷'), ('South Africa', '南非'), ('Egypt', '埃及'), ('Nigeria', '奈及利亞'), ('Australia', '澳洲'), ('New Zealand', '紐西蘭'), ('Other', '其他')], default='', help_text='留空表示所有國籍通用；各國做法不同的內容（簽證辦理）請指定國籍', max_length=50, verbose_name='適用國籍'),
        ),
        migrations.AddField(
            model_name='chatknowledge',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('overseas_chinese', '僑生'), ('foreign_student', '外籍生'), ('hong_kong_macau', '港澳生')], default='', help_text='留空表示僑生／外籍生／港澳生皆適用；管道不同的內容請指定身分別', max_length=30, verbose_name='適用身分別'),
        ),
        migrations.AddField(
            model_name='chatknowledge',
            name='university',
            field=models.CharField(blank=True, choices=[('NTU', '國立臺灣大學（NTU）'), ('NCCU', '國立政治大學（NCCU）'), ('NTHU', '國立清華大學（NTHU）'), ('NYCU', '國立陽明交通大學（NYCU）'), ('NCKU', '國立成功大學（NCKU）'), ('NCHU', '國立中興大學（NCHU）'), ('NCU', '國立中央大學（NCU）'), ('NSYSU', '國立中山大學（NSYSU）'), ('NTNU', '國立臺灣師範大學（NTNU）'), ('NTPU', '國立臺北大學（NTPU）'), ('NUTN', '國立臺南大學（NUTN）'), ('NCYU', '國立嘉義大學（NCYU）'), ('NDHU', '國立東華大學（NDHU）'), ('NCNU', '國立暨南國際大學（NCNU）'), ('NIU', '國立宜蘭大學（NIU）'), ('NUU', '國立聯合大學（NUU）'), ('NTTU', '國立臺東大學（NTTU）'), ('NQU', '國立金門大學（NQU）'), ('NPU', '國立澎湖科技大學（NPU）'), ('NTUST', '國立臺灣科技大學（NTUST）'), ('NTUT', '國立臺北科技大學（NTUT）'), ('NKUST', '國立高雄科技大學（NKUST）'), ('YunTech', '國立雲林科技大學（YunTech）'), ('NPUST', '國立屏東科技大學（NPUST）'), ('NTCUST', '國立臺中科技大學（NTCUST）'), ('NFU', '國立虎尾科技大學（NFU）'), ('NKUHT', '國立高雄餐旅大學（NKUHT）'), ('NKNU', '國立高雄師範大學（NKNU）'), ('NCUE', '國立彰化師範大學（NCUE）'), ('NTUE', '國立臺北教育大學（NTUE）'), ('NTCU', '國立臺中教育大學（NTCU）'), ('NPTU', '國立屏東大學（NPTU）'), ('NTUS', '國立臺灣體育運動大學（NTUS）'), ('NTUB', '國立臺北商業大學（NTUB）'), ('NOU', '國立空中大學（NOU）'), ('Other', '其他（Other）')], default='', help_text='留空表示所有學校通用；各校做法不同的內容（入學申請、註冊繳費等）請指定學校', max_length=200, verbose_name='適用學校'),
        ),
        migrations.AlterField(
            model_name='chatknowledge',
            name='category',
            field=models.CharField(choices=[('school_info', '學校資訊'), ('admission', '入學申請'), ('documents', '文件準備'), ('document_verification', '文件驗證'), ('visa', '簽證'), ('financial_proof', '財力證明'), ('language_proof', '語言證明'), ('before_arrival', '來台前準備'), ('entry', '入境規定'), ('country_difference', '國家差異'), ('identity_type', '身分別流程'), ('arrival_transport', '到校交通'), ('orientation', '新生報到'), ('registration_payment', '註冊繳費'), ('student_id', '學生證'), ('arc', '居留證 ARC'), ('health_check', '健檢'), ('insurance', '保險'), ('bank', '銀行開戶'), ('phone', '手機門號'), ('school_system', '校內系統'), ('course', '課務選課'), ('student_status', '學籍'), ('grades', '成績'), ('graduation', '畢業'), ('dorm', '宿舍'), ('renting', '租屋'), ('nhi', '健保'), ('work_permit', '工作證'), ('scholarship', '獎助學金'), ('campus_activity', '校內活動'), ('library', '圖書館'), ('internship', '交換與實習'), ('admin_documents', '行政文件'), ('transportation', '交通'), ('food', '飲食'), ('medical', '醫療'), ('mental_support', '心理支持'), ('emergency', '緊急聯絡'), ('living_cost', '生活費'), ('other', '其他')], default='other', max_length=50, verbose_name='分類'),
        ),
    ]
