# Generated by Django 6.0.4 on 2026-09-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_chatknowledge_country_chatknowledge_identity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatknowledge',
            name='bot_type',
            field=models.CharField(choices=[('helper', 'Assistant'), ('friend', 'friend'), ('both', '兩者都可使用')], default='helper', max_length=20, verbose_name='適用 AI'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_mode',
            field=models.CharField(choices=[('helper', 'Assistant'), ('friend', 'friend')], default='helper', max_length=20, verbose_name='AI 模式'),
        ),
    ]
