# Generated by Django 4.2.30 on 2026-04-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程階段名稱')),
                ('description', models.TextField(blank=True, verbose_name='階段說明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'db_table': 'flows_stage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任務名稱')),
                ('description', models.TextField(blank=True, verbose_name='任務說明')),
                ('identity_type', models.CharField(blank=True, choices=[('overseas_chinese', '僑生（海外華裔）'), ('foreign_student', '外籍生（一般外國學生）'), ('exchange', '交換生'), ('preparatory', '僑大先修生')], max_length=30, verbose_name='適用身份別')),
                ('nationality', models.CharField(blank=True, choices=[('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Japan', '日本'), ('Korea', '韓國'), ('Other', '其他')], max_length=50, verbose_name='適用國籍')),
                ('admission_status', models.CharField(blank=True, choices=[('applied', '已提出申請'), ('admitted', '已收到錄取通知'), ('pre_arrival', '入境前準備中'), ('arrived', '已抵臺就學中')], max_length=20, verbose_name='適用入學狀態')),
                ('official_url', models.URLField(blank=True, verbose_name='官方資料連結')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必做')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flows.flowstage', verbose_name='所屬流程階段')),
            ],
            options={
                'db_table': 'flows_task',
                'ordering': ['stage__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '進行中'), ('completed', '已完成')], default='not_started', max_length=20, verbose_name='完成狀態')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tasks', to='users.studentprofile', verbose_name='學生')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tasks', to='flows.task', verbose_name='任務')),
            ],
            options={
                'db_table': 'flows_student_task',
                'unique_together': {('student', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='提醒內容')),
                ('remind_date', models.DateField(blank=True, null=True, verbose_name='提醒日期')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('student_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='flows.studenttask', verbose_name='學生任務')),
            ],
            options={
                'db_table': 'flows_reminder',
                'ordering': ['remind_date'],
            },
        ),
    ]
