# Generated by Django 4.2.30 on 2026-04-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
