# Generated by Django 4.2.30 on 2026-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_delete_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admission_status',
            field=models.CharField(blank=True, choices=[('pre_arrival', '入境前準備中'), ('arrived', '已抵臺就學中')], max_length=20, verbose_name='適用入學狀態'),
        ),
        migrations.AlterField(
            model_name='task',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('overseas_chinese_student', '僑生（海外華裔）'), ('foreign_student', '外籍生（一般外國學生）')], max_length=30, verbose_name='適用身份別'),
        ),
    ]
