# Generated by Django 4.2.30 on 2026-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_alter_task_admission_status_alter_task_identity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstage',
            name='description_my',
            field=models.TextField(blank=True, verbose_name='階段說明-緬文'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='name_my',
            field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱-緬文'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_my',
            field=models.TextField(blank=True, verbose_name='任務說明-緬文'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_my',
            field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱-緬文'),
        ),
        migrations.AlterField(
            model_name='task',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('overseas_chinese', '僑生（海外華裔）'), ('foreign_student', '外籍生（一般外國學生）'), ('hong_kong_macau', '港澳生')], max_length=30, verbose_name='適用身份別'),
        ),
    ]
