# Generated by Django 6.0.4 on 2026-05-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_flowstage_description_my_flowstage_name_my_and_more'),
        ('users', '0003_alter_studentprofile_admission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計完成日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='admission_status',
            field=models.CharField(blank=True, choices=[('pre_arrival', '入臺前準備'), ('arrived', '抵臺後')], max_length=20, verbose_name='適用入學狀態'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='提醒內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.studentprofile', verbose_name='學生')),
                ('student_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='flows.studenttask', verbose_name='關聯學生任務')),
            ],
            options={
                'db_table': 'flows_reminder',
                'ordering': ['-created_at'],
            },
        ),
    ]
