# Generated by Django 6.0.4 on 2026-05-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0005_studenttask_due_date_alter_task_admission_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowstage',
            name='description_my',
        ),
        migrations.RemoveField(
            model_name='flowstage',
            name='name_my',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_my',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title_my',
        ),
    ]
