# Generated by Django 4.2.30 on 2026-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0006_remove_flowstage_description_my_and_more'),
    ]

    operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.AddField(
                model_name='flowstage',
                name='description_my',
                field=models.TextField(blank=True, verbose_name='階段說明 Burmese'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_my',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Burmese'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_my',
                field=models.TextField(blank=True, verbose_name='任務說明 Burmese'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_my',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Burmese'),
            ),
        ],
        state_operations=[
            migrations.AddField(
                model_name='flowstage',
                name='description_en',
                field=models.TextField(blank=True, verbose_name='階段說明 English'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='description_id',
                field=models.TextField(blank=True, verbose_name='階段說明 Indonesian'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='description_ja',
                field=models.TextField(blank=True, verbose_name='階段說明 Japanese'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='description_ms',
                field=models.TextField(blank=True, verbose_name='階段說明 Malay'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='description_my',
                field=models.TextField(blank=True, verbose_name='階段說明 Burmese'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='description_th',
                field=models.TextField(blank=True, verbose_name='階段說明 Thai'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_en',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 English'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_id',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Indonesian'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_ja',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Japanese'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_ms',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Malay'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_my',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Burmese'),
            ),
            migrations.AddField(
                model_name='flowstage',
                name='name_th',
                field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Thai'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_en',
                field=models.TextField(blank=True, verbose_name='任務說明 English'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_id',
                field=models.TextField(blank=True, verbose_name='任務說明 Indonesian'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_ja',
                field=models.TextField(blank=True, verbose_name='任務說明 Japanese'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_ms',
                field=models.TextField(blank=True, verbose_name='任務說明 Malay'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_my',
                field=models.TextField(blank=True, verbose_name='任務說明 Burmese'),
            ),
            migrations.AddField(
                model_name='task',
                name='description_th',
                field=models.TextField(blank=True, verbose_name='任務說明 Thai'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_en',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 English'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_id',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Indonesian'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_ja',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Japanese'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_ms',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Malay'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_my',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Burmese'),
            ),
            migrations.AddField(
                model_name='task',
                name='title_th',
                field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Thai'),
            ),
            migrations.AlterField(
                model_name='task',
                name='identity_type',
                field=models.CharField(
                    blank=True,
                    choices=[
                        ('overseas_chinese', '僑生'),
                        ('foreign_student', '外籍生'),
                        ('hong_kong_macau', '港澳生'),
                    ],
                    max_length=30,
                    verbose_name='適用身份類型',
                ),
            ),
            migrations.AlterField(
                model_name='task',
                name='official_url',
                field=models.URLField(blank=True, verbose_name='官方資源連結'),
            ),
        ],
    ),
]
