# Generated by Django 4.2.30 on 2026-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0007_flowstage_description_en_flowstage_description_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='note',
            field=models.TextField(blank=True, verbose_name='任務備註'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents',
            field=models.TextField(blank=True, verbose_name='需要的文件'),
        ),
    ]
