# Generated by Django 4.2.30 on 2026-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_studenttask_note_task_apply_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttask',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='抵台後幾天內必須完成，例如填 30 代表抵台後 30 天', null=True, verbose_name='計算天數（僅限 from_arrival 使用）'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text',
            field=models.CharField(blank=True, help_text='顯示給學生看的說明文字，例如：請於抵台後 30 天內完成居留證申請', max_length=300, verbose_name='辦理時程文字'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_type',
            field=models.CharField(choices=[('none', '無截止日期'), ('text_only', '只顯示文字說明'), ('from_arrival', '依抵台日期自動計算')], default='none', max_length=20, verbose_name='期限類型'),
        ),
    ]
