# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_studenttask_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstage',
            name='description_ko',
            field=models.TextField(blank=True, verbose_name='階段說明 Korean'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='name_ko',
            field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ko',
            field=models.TextField(blank=True, verbose_name='任務說明 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ko',
            field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Korean'),
        ),
    ]