# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):
    # Fields already added by 0013_flowstage_description_ko_flowstage_name_ko_and_more

    dependencies = [
        ('flows', '0008_studenttask_note'),
    ]

    operations = []