# Generated by Django 4.2.30 on 2026-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_remove_studenttask_due_date_task_deadline_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='apply_map_url',
            field=models.URLField(blank=True, help_text='Google Maps 或其他地圖連結，例如：https://maps.google.com/?q=...', verbose_name='辦理地點地圖連結'),
        ),
    ]
