# Generated by Django 4.2.30 on 2026-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0010_task_apply_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='apply_location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 English'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Indonesian'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location_ja',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Japanese'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location_ms',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Malay'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location_my',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Burmese'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location_th',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Thai'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 English'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Indonesian'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_ja',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Japanese'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_ms',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Malay'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_my',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Burmese'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_th',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Thai'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_en',
            field=models.TextField(blank=True, verbose_name='需要的文件 English'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_id',
            field=models.TextField(blank=True, verbose_name='需要的文件 Indonesian'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_ja',
            field=models.TextField(blank=True, verbose_name='需要的文件 Japanese'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_ms',
            field=models.TextField(blank=True, verbose_name='需要的文件 Malay'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_my',
            field=models.TextField(blank=True, verbose_name='需要的文件 Burmese'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_th',
            field=models.TextField(blank=True, verbose_name='需要的文件 Thai'),
        ),
        migrations.AlterField(
            model_name='task',
            name='apply_map_url',
            field=models.URLField(blank=True, help_text='Google Maps 或其他地圖連結', verbose_name='辦理地點地圖連結'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='抵台後幾天內必須完成', null=True, verbose_name='計算天數（僅限 from_arrival 使用）'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字'),
        ),
    ]
