# Generated by Django 6.0.4 on 2026-05-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_flowstage_description_ko_flowstage_name_ko_and_more'),
        ('flows', '0011_task_apply_location_en_task_apply_location_id_and_more'),
    ]

    operations = [
    ]
