# Generated by Django 4.2.30 on 2026-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_studenttask_note'),
        ('flows', '0011_task_apply_location_en_task_apply_location_id_and_more'),
    ]

    operations = [
    ]
