# Generated by Django 4.2.30 on 2026-05-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0012_merge_20260513_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstage',
            name='description_ko',
            field=models.TextField(blank=True, verbose_name='階段說明 Korean'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='name_ko',
            field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ko',
            field=models.TextField(blank=True, verbose_name='任務說明 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ko',
            field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='university',
            field=models.CharField(blank=True, choices=[('NTU', '國立臺灣大學（NTU）'), ('NCCU', '國立政治大學（NCCU）'), ('NTHU', '國立清華大學（NTHU）'), ('NYCU', '國立陽明交通大學（NYCU）'), ('NCKU', '國立成功大學（NCKU）'), ('NCHU', '國立中興大學（NCHU）'), ('NCU', '國立中央大學（NCU）'), ('NSYSU', '國立中山大學（NSYSU）'), ('NTNU', '國立臺灣師範大學（NTNU）'), ('NTPU', '國立臺北大學（NTPU）'), ('NUTN', '國立臺南大學（NUTN）'), ('NCYU', '國立嘉義大學（NCYU）'), ('NDHU', '國立東華大學（NDHU）'), ('NCNU', '國立暨南國際大學（NCNU）'), ('NIU', '國立宜蘭大學（NIU）'), ('NUU', '國立聯合大學（NUU）'), ('NTTU', '國立臺東大學（NTTU）'), ('NQU', '國立金門大學（NQU）'), ('NPU', '國立澎湖科技大學（NPU）'), ('NTUST', '國立臺灣科技大學（NTUST）'), ('NTUT', '國立臺北科技大學（NTUT）'), ('NKUST', '國立高雄科技大學（NKUST）'), ('YunTech', '國立雲林科技大學（YunTech）'), ('NPUST', '國立屏東科技大學（NPUST）'), ('NTCUST', '國立臺中科技大學（NTCUST）'), ('NFU', '國立虎尾科技大學（NFU）'), ('NKUHT', '國立高雄餐旅大學（NKUHT）'), ('NKNU', '國立高雄師範大學（NKNU）'), ('NCUE', '國立彰化師範大學（NCUE）'), ('NTUE', '國立臺北教育大學（NTUE）'), ('NTCU', '國立臺中教育大學（NTCU）'), ('NPTU', '國立屏東大學（NPTU）'), ('NTUS', '國立臺灣體育運動大學（NTUS）'), ('NTUB', '國立臺北商業大學（NTUB）'), ('NOU', '國立空中大學（NOU）'), ('Other', '其他（Other）')], max_length=200, verbose_name='適用學校'),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='note',
            field=models.TextField(blank=True, verbose_name='任務備註'),
        ),
    ]
