# Generated by Django 4.2.30 on 2026-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0013_flowstage_description_ko_flowstage_name_ko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='apply_location_ko',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_ko',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_ko',
            field=models.TextField(blank=True, verbose_name='需要的文件 Korean'),
        ),
    ]
