# Generated by Django 6.0.4 on 2026-05-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0012_merge_20260513_2036'),
        ('flows', '0014_task_apply_location_ko_task_deadline_text_ko_and_more'),
    ]

    operations = [
    ]
