# Generated by Django 4.2.30 on 2026-05-15 17:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0014_task_apply_location_ko_task_deadline_text_ko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identity_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('overseas_chinese', '僑生'), ('foreign_student', '外籍生'), ('hong_kong_macau', '港澳生')], max_length=48, null=True, verbose_name='適用身份類型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='nationality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Japan', '日本'), ('Korea', '韓國'), ('Other', '其他')], max_length=82, null=True, verbose_name='適用國籍'),
        ),
    ]
