# Generated by Django 4.2.30 on 2026-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0016_task_region_alter_task_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, default='', help_text='用來判斷同一類任務，例如 prepare_passport、apply_visa。學生前端不會顯示。', max_length=100, verbose_name='任務代碼'),
        ),
    ]
