# Generated by Django 6.0.4 on 2026-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0015_merge_20260515_2140'),
        ('flows', '0017_task_task_code'),
    ]

    operations = [
    ]
