# Generated by Django 4.2.30 on 2026-05-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0017_task_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstage',
            name='description_vi',
            field=models.TextField(blank=True, verbose_name='階段說明 Vietnamese'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100, verbose_name='流程階段名稱 Vietnamese'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_location_vi',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地點 Vietnamese'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_text_vi',
            field=models.CharField(blank=True, max_length=300, verbose_name='辦理時程文字 Vietnamese'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_vi',
            field=models.TextField(blank=True, verbose_name='任務說明 Vietnamese'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_documents_vi',
            field=models.TextField(blank=True, verbose_name='需要的文件 Vietnamese'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_vi',
            field=models.CharField(blank=True, max_length=200, verbose_name='任務名稱 Vietnamese'),
        ),
    ]
