# Generated by Django 4.2.30 on 2026-05-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0018_flowstage_description_vi_flowstage_name_vi_and_more'),
        ('flows', '0018_merge_0015_merge_20260515_2140_0017_task_task_code'),
    ]

    operations = [
    ]
