# Generated by Django 4.2.30 on 2026-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0019_merge_20260520_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內容說明')),
                ('official_url', models.URLField(blank=True, verbose_name='官方網站連結')),
                ('icon', models.CharField(blank=True, default='💡', help_text='顯示在標題前方的 Emoji，例如 💡📚🏥', max_length=10, verbose_name='圖示 Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='標題 English')),
                ('title_my', models.CharField(blank=True, max_length=200, verbose_name='標題 Burmese')),
                ('title_id', models.CharField(blank=True, max_length=200, verbose_name='標題 Indonesian')),
                ('title_ms', models.CharField(blank=True, max_length=200, verbose_name='標題 Malay')),
                ('title_th', models.CharField(blank=True, max_length=200, verbose_name='標題 Thai')),
                ('title_ja', models.CharField(blank=True, max_length=200, verbose_name='標題 Japanese')),
                ('title_ko', models.CharField(blank=True, max_length=200, verbose_name='標題 Korean')),
                ('title_vi', models.CharField(blank=True, max_length=200, verbose_name='標題 Vietnamese')),
                ('content_en', models.TextField(blank=True, verbose_name='內容 English')),
                ('content_my', models.TextField(blank=True, verbose_name='內容 Burmese')),
                ('content_id', models.TextField(blank=True, verbose_name='內容 Indonesian')),
                ('content_ms', models.TextField(blank=True, verbose_name='內容 Malay')),
                ('content_th', models.TextField(blank=True, verbose_name='內容 Thai')),
                ('content_ja', models.TextField(blank=True, verbose_name='內容 Japanese')),
                ('content_ko', models.TextField(blank=True, verbose_name='內容 Korean')),
                ('content_vi', models.TextField(blank=True, verbose_name='內容 Vietnamese')),
            ],
            options={
                'verbose_name': '小貼士',
                'verbose_name_plural': '小貼士',
                'db_table': 'flows_tip',
                'ordering': ['order'],
            },
        ),
    ]
