# Generated by Django 4.2.30 on 2026-05-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0020_tip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['order'], 'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
        migrations.RemoveField(
            model_name='tip',
            name='icon',
        ),
    ]
