# Generated by Django 4.2.30 on 2026-05-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0021_alter_tip_options_remove_tip_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='official_url',
        ),
        migrations.CreateModel(
            name='TipLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='鏈結網址')),
                ('label', models.CharField(blank=True, help_text='留空則直接使用 URL 作為顯示文字', max_length=120, verbose_name='鏈結顯示文字')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='flows.tip', verbose_name='所屬小貼士')),
            ],
            options={
                'verbose_name': '小貼士鏈結',
                'verbose_name_plural': '小貼士鏈結',
                'db_table': 'flows_tip_link',
                'ordering': ['id'],
            },
        ),
    ]
