# Generated by Django 4.2.30 on 2026-06-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0022_remove_tip_official_url_tiplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='require_deferred',
            field=models.BooleanField(blank=True, help_text='勾選「是」→僅延遲入學者可見；勾選「否」→僅非延遲入學者可見；留空→不限制', null=True, verbose_name='是否限延遲入學者'),
        ),
        migrations.AddField(
            model_name='task',
            name='require_indo_prep',
            field=models.BooleanField(blank=True, help_text='勾選「是」→僅上印輔班者可見；勾選「否」→僅未上印輔班者可見；留空→不限制', null=True, verbose_name='是否限上印輔班者'),
        ),
        migrations.AddField(
            model_name='task',
            name='require_taiwan_id',
            field=models.BooleanField(blank=True, help_text='勾選「是」→僅有身分證者可見；勾選「否」→僅無身分證者可見；留空→不限制', null=True, verbose_name='是否限有台灣身份證者'),
        ),
    ]
