# Generated by Django 4.2.30 on 2026-06-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0023_task_require_deferred_task_require_indo_prep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='require_indo_prep',
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 English'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Indonesian'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_ja',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Japanese'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_ko',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Korean'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_ms',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Malay'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_my',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Burmese'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_th',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Thai'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='label_vi',
            field=models.CharField(blank=True, max_length=120, verbose_name='鏈結文字 Vietnamese'),
        ),
    ]
