# Generated by Django 4.2.30 on 2026-06-15 08:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0024_remove_task_require_indo_prep_tiplink_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='identity_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('overseas_chinese', '僑生'), ('foreign_student', '外籍生'), ('hong_kong_macau', '港澳生')], help_text='留空表示適用於所有身份', max_length=48, null=True, verbose_name='適用身份類型'),
        ),
    ]
