# Generated by Django 4.2.30 on 2026-06-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0025_tip_identity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiplink',
            name='category',
            field=models.CharField(blank=True, help_text='可自訂分類名稱，例如：官方網站、參考資料等', max_length=100, verbose_name='鏈結分類'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 English'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Indonesian'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_ja',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Japanese'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_ko',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Korean'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_ms',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Malay'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_my',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Burmese'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_th',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Thai'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_vi',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Vietnamese'),
        ),
    ]
