# Generated by Django 4.2.30 on 2026-06-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0026_tiplink_category_tiplink_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiplink',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_ja',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_ko',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_ms',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_my',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_th',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_vi',
        ),
    ]
