# Generated by Django 4.2.30 on 2026-06-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0027_remove_tiplink_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiplink',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Indonesian'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_ja',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Japanese'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_ko',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Korean'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_ms',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Malay'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_my',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Burmese'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_th',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Thai'),
        ),
        migrations.AddField(
            model_name='tiplink',
            name='category_vi',
            field=models.CharField(blank=True, max_length=100, verbose_name='分類名稱 Vietnamese'),
        ),
    ]
