# Generated by Django 4.2.30 on 2026-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0028_tiplink_category_id_tiplink_category_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiplink',
            name='category_icon',
            field=models.CharField(blank=True, help_text='請輸入 Google Material Icon 名稱，例如: restaurant', max_length=50, verbose_name='分類圖示'),
        ),
    ]
