# Generated by Django 4.2.30 on 2026-06-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0029_tiplink_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='分類名稱 English')),
                ('icon', models.CharField(blank=True, help_text='請輸入 Google Material Icon 名稱，例如: restaurant', max_length=50, verbose_name='分類圖示')),
            ],
            options={
                'verbose_name': '小貼士連結分類',
                'verbose_name_plural': '小貼士連結分類',
                'db_table': 'flows_tip_link_category',
            },
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_icon',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_ja',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_ko',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_ms',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_my',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_th',
        ),
        migrations.RemoveField(
            model_name='tiplink',
            name='category_vi',
        ),
        migrations.AddField(
            model_name='tiplink',
            name='link_category',
            field=models.ForeignKey(blank=True, help_text='請選擇分類，若不需分類請留空', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.tiplinkcategory', verbose_name='鏈結分類'),
        ),
    ]
