# Generated by Django 6.0.4 on 2026-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0030_tiplinkcategory_remove_tiplink_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='特定截止日期（僅限 absolute 使用）', null=True, verbose_name='固定截止日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_days',
            field=models.IntegerField(blank=True, help_text='計算天數（正數為抵台後，負數為抵台前）', null=True, verbose_name='計算天數（僅限 from_arrival 使用）'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_type',
            field=models.CharField(choices=[('none', '無截止日期'), ('text_only', '只顯示文字說明'), ('from_arrival', '依抵台日期自動計算（正數為抵台後，負數為抵台前）'), ('absolute', '固定截止日期')], default='none', max_length=20, verbose_name='期限類型'),
        ),
    ]
