# Generated by Django 6.0.4 on 2026-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0031_task_deadline_date_alter_task_deadline_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstage',
            name='is_pre_arrival',
            field=models.BooleanField(default=False, help_text='勾選後，選擇「已抵臺」的學生會自動將此階段的任務標記為已完成', verbose_name='是否為入臺前階段'),
        ),
    ]
