# Generated by Django 6.0.4 on 2026-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0033_set_is_pre_arrival_from_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='apply_address_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 English'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Indonesian'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_ja',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Japanese'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_ko',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Korean'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_ms',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Malay'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_my',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Burmese'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_th',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Thai'),
        ),
        migrations.AddField(
            model_name='task',
            name='apply_address_vi',
            field=models.CharField(blank=True, max_length=200, verbose_name='辦理地址 Vietnamese'),
        ),
    ]
