# Generated by Django 6.0.4 on 2026-07-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0034_task_apply_address_en_task_apply_address_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(blank=True, help_text='kind 為 due_soon/due_today/overdue 時使用', null=True, verbose_name='相關截止日期'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='kind',
            field=models.CharField(blank=True, choices=[('due_soon', '即將到期'), ('due_today', '今天到期'), ('overdue', '已過期'), ('skipped', '跳過前置任務')], default='', help_text='用來讓小鈴鐺依目前瀏覽語言即時翻譯提醒內容；舊資料留空，會直接顯示 message 欄位。', max_length=20, verbose_name='提醒類型'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='skipped_task_ids',
            field=models.JSONField(blank=True, default=list, help_text='kind 為 skipped 時使用', verbose_name='被跳過的前置任務ID'),
        ),
    ]
