# Generated by Django 6.0.4 on 2026-08-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0036_reminder_proactive_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='用來讓排程補寄：即使這筆提醒已經存在（例如使用者自己開網站時即時建立、未寄信），只要這裡是 False，下次 check_reminders 執行時還是會補寄一次。', verbose_name='是否已成功寄送 Email'),
        ),
    ]
