# Generated by Django 6.0.4 on 2026-10-03 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0018_chatknowledge_country_chatknowledge_identity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='資料日期')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='模擬資料')),
                ('student_key', models.CharField(db_index=True, max_length=32, verbose_name='學生代碼（雜湊）')),
                ('university', models.CharField(db_index=True, max_length=200, verbose_name='學校')),
                ('nationality', models.CharField(max_length=50, verbose_name='國籍')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='地區')),
                ('identity_type', models.CharField(max_length=30, verbose_name='身份別')),
                ('arrival_cohort', models.CharField(blank=True, help_text='例：2026-09；空白＝未填抵台日', max_length=7, verbose_name='抵台梯次')),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, help_text='民國年，例：115', null=True, verbose_name='學年度')),
                ('admission_status', models.CharField(max_length=20, verbose_name='入學狀態')),
                ('preferred_language', models.CharField(blank=True, max_length=10, verbose_name='偏好語言')),
            ],
            options={
                'verbose_name': '分析表：學生',
                'verbose_name_plural': '分析表：學生',
                'db_table': 'insights_dim_student',
            },
        ),
        migrations.CreateModel(
            name='FactQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='資料日期')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='模擬資料')),
                ('student_key', models.CharField(db_index=True, max_length=32, verbose_name='學生代碼（雜湊）')),
                ('university', models.CharField(db_index=True, max_length=200, verbose_name='學校')),
                ('nationality', models.CharField(max_length=50, verbose_name='國籍')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='地區')),
                ('identity_type', models.CharField(max_length=30, verbose_name='身份別')),
                ('arrival_cohort', models.CharField(blank=True, help_text='例：2026-09；空白＝未填抵台日', max_length=7, verbose_name='抵台梯次')),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, help_text='民國年，例：115', null=True, verbose_name='學年度')),
                ('category', models.CharField(choices=[('entry_permit', '簽證／入出境許可'), ('residence_permit', '居留證件'), ('nhi', '全民健保'), ('housing', '住宿'), ('registration', '報到註冊'), ('health_check', '健康檢查'), ('course', '選課'), ('bank', '銀行開戶'), ('work_permit', '工作許可'), ('scholarship', '獎助學金'), ('medical', '就醫'), ('daily_life', '生活（交通、手機、飲食）'), ('other', '其他')], max_length=30, verbose_name='提問分類')),
                ('asked_date', models.DateField(verbose_name='提問日期')),
            ],
            options={
                'verbose_name': '分析表：學生提問',
                'verbose_name_plural': '分析表：學生提問',
                'db_table': 'insights_fact_question',
            },
        ),
        migrations.CreateModel(
            name='FactStudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='資料日期')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='模擬資料')),
                ('student_key', models.CharField(db_index=True, max_length=32, verbose_name='學生代碼（雜湊）')),
                ('university', models.CharField(db_index=True, max_length=200, verbose_name='學校')),
                ('nationality', models.CharField(max_length=50, verbose_name='國籍')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='地區')),
                ('identity_type', models.CharField(max_length=30, verbose_name='身份別')),
                ('arrival_cohort', models.CharField(blank=True, help_text='例：2026-09；空白＝未填抵台日', max_length=7, verbose_name='抵台梯次')),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, help_text='民國年，例：115', null=True, verbose_name='學年度')),
                ('task_category', models.CharField(choices=[('entry_permit', '簽證／入出境許可'), ('residence_permit', '居留證件'), ('nhi', '全民健保'), ('housing', '住宿'), ('registration', '報到註冊'), ('health_check', '健康檢查'), ('course', '選課'), ('other', '其他')], max_length=30, verbose_name='任務分類')),
                ('is_required', models.BooleanField(verbose_name='必做')),
                ('has_deadline', models.BooleanField(verbose_name='有截止日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日')),
                ('status', models.CharField(max_length=20, verbose_name='完成狀態')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('is_completed', models.BooleanField(verbose_name='已完成')),
                ('is_due', models.BooleanField(help_text='截止日 ≤ 資料日期', verbose_name='已到期')),
                ('is_overdue_open', models.BooleanField(verbose_name='逾期未完成')),
                ('is_overdue_late', models.BooleanField(verbose_name='逾期完成')),
                ('is_overdue', models.BooleanField(verbose_name='逾期')),
                ('is_possibly_unreported', models.BooleanField(verbose_name='可能未回報')),
                ('reminder_count', models.PositiveSmallIntegerField(default=0, verbose_name='到期前提醒次數')),
            ],
            options={
                'verbose_name': '分析表：學生任務',
                'verbose_name_plural': '分析表：學生任務',
                'db_table': 'insights_fact_student_task',
            },
        ),
        migrations.CreateModel(
            name='InsightAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='資料日期')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='模擬資料')),
                ('university', models.CharField(db_index=True, max_length=200, verbose_name='學校')),
                ('task_category', models.CharField(choices=[('entry_permit', '簽證／入出境許可'), ('residence_permit', '居留證件'), ('nhi', '全民健保'), ('housing', '住宿'), ('registration', '報到註冊'), ('health_check', '健康檢查'), ('course', '選課'), ('other', '其他')], max_length=30, verbose_name='任務分類')),
                ('baseline_type', models.CharField(choices=[('yoy', '前一學年度'), ('cohort', '上一個抵台梯次'), ('group', '整體平均')], max_length=10, verbose_name='比較基準')),
                ('current_label', models.CharField(max_length=60, verbose_name='目前期間／族群')),
                ('current_rate', models.FloatField(verbose_name='目前逾期率')),
                ('current_n', models.PositiveIntegerField(verbose_name='目前分母')),
                ('baseline_label', models.CharField(max_length=60, verbose_name='比較基準期間／族群')),
                ('baseline_rate', models.FloatField(verbose_name='基準逾期率')),
                ('baseline_n', models.PositiveIntegerField(verbose_name='基準分母')),
                ('delta_pp', models.FloatField(verbose_name='變化（百分點）')),
                ('concentrated_groups', models.JSONField(default=list, verbose_name='逾期集中族群')),
                ('reminder_effect', models.JSONField(default=dict, verbose_name='提醒成效參考')),
                ('recommendation', models.TextField(verbose_name='行動建議')),
            ],
            options={
                'verbose_name': '分析表：風險預警',
                'verbose_name_plural': '分析表：風險預警',
                'db_table': 'insights_alert',
                'ordering': ['-delta_pp'],
            },
        ),
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='資料日期')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='模擬資料')),
                ('powerbi_upn', models.CharField(max_length=254, verbose_name='Power BI 登入帳號')),
                ('university', models.CharField(max_length=200, verbose_name='學校')),
            ],
            options={
                'verbose_name': '分析表：Power BI 權限對照',
                'verbose_name_plural': '分析表：Power BI 權限對照',
                'db_table': 'insights_staff_access',
            },
        ),
        migrations.CreateModel(
            name='QuestionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('entry_permit', '簽證／入出境許可'), ('residence_permit', '居留證件'), ('nhi', '全民健保'), ('housing', '住宿'), ('registration', '報到註冊'), ('health_check', '健康檢查'), ('course', '選課'), ('bank', '銀行開戶'), ('work_permit', '工作許可'), ('scholarship', '獎助學金'), ('medical', '就醫'), ('daily_life', '生活（交通、手機、飲食）'), ('other', '其他')], max_length=30, verbose_name='分類')),
                ('method', models.CharField(choices=[('rule', '關鍵字規則'), ('llm', 'LLM'), ('none', '未分類')], max_length=10, verbose_name='分類方式')),
                ('classified_at', models.DateTimeField(auto_now_add=True, verbose_name='分類時間')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights_classification', to='chatbot.chatmessage', verbose_name='提問訊息')),
            ],
            options={
                'verbose_name': 'AI 提問分類',
                'verbose_name_plural': 'AI 提問分類',
                'db_table': 'insights_question_classification',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('NTU', '國立臺灣大學（NTU）'), ('NCCU', '國立政治大學（NCCU）'), ('NTHU', '國立清華大學（NTHU）'), ('NYCU', '國立陽明交通大學（NYCU）'), ('NCKU', '國立成功大學（NCKU）'), ('NCHU', '國立中興大學（NCHU）'), ('NCU', '國立中央大學（NCU）'), ('NSYSU', '國立中山大學（NSYSU）'), ('NTNU', '國立臺灣師範大學（NTNU）'), ('NTPU', '國立臺北大學（NTPU）'), ('NUTN', '國立臺南大學（NUTN）'), ('NCYU', '國立嘉義大學（NCYU）'), ('NDHU', '國立東華大學（NDHU）'), ('NCNU', '國立暨南國際大學（NCNU）'), ('NIU', '國立宜蘭大學（NIU）'), ('NUU', '國立聯合大學（NUU）'), ('NTTU', '國立臺東大學（NTTU）'), ('NQU', '國立金門大學（NQU）'), ('NPU', '國立澎湖科技大學（NPU）'), ('NTUST', '國立臺灣科技大學（NTUST）'), ('NTUT', '國立臺北科技大學（NTUT）'), ('NKUST', '國立高雄科技大學（NKUST）'), ('YunTech', '國立雲林科技大學（YunTech）'), ('NPUST', '國立屏東科技大學（NPUST）'), ('NTCUST', '國立臺中科技大學（NTCUST）'), ('NFU', '國立虎尾科技大學（NFU）'), ('NKUHT', '國立高雄餐旅大學（NKUHT）'), ('NKNU', '國立高雄師範大學（NKNU）'), ('NCUE', '國立彰化師範大學（NCUE）'), ('NTUE', '國立臺北教育大學（NTUE）'), ('NTCU', '國立臺中教育大學（NTCU）'), ('NPTU', '國立屏東大學（NPTU）'), ('NTUS', '國立臺灣體育運動大學（NTUS）'), ('NTUB', '國立臺北商業大學（NTUB）'), ('NOU', '國立空中大學（NOU）'), ('Other', '其他（Other）')], max_length=200, verbose_name='所屬學校')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='職稱')),
                ('powerbi_upn', models.EmailField(blank=True, help_text='此人登入 Power BI 使用的學校 Microsoft 帳號（UPN），用於 Power BI 列層級安全性（RLS）。', max_length=254, verbose_name='Power BI 登入帳號')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights_staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='帳號')),
            ],
            options={
                'verbose_name': '校方人員',
                'verbose_name_plural': '校方人員',
                'db_table': 'insights_staff_profile',
            },
        ),
    ]
