# Generated by Django 6.0.4 on 2026-10-06 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightAskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='學校代碼或 ALL', max_length=200, verbose_name='權限範圍')),
                ('question', models.TextField(verbose_name='問題')),
                ('tool_calls', models.JSONField(default=list, verbose_name='工具呼叫與結果')),
                ('answer', models.TextField(blank=True, verbose_name='回答')),
                ('source', models.CharField(choices=[('llm', 'AI 回答'), ('preset', '預設問題卡片'), ('error', '失敗')], max_length=10, verbose_name='來源')),
                ('verified', models.BooleanField(default=True, help_text='回答中的數字是否都能在工具結果中找到', verbose_name='數字已驗證')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提問時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_ask_logs', to=settings.AUTH_USER_MODEL, verbose_name='提問者')),
            ],
            options={
                'verbose_name': 'AI 資料助理紀錄',
                'verbose_name_plural': 'AI 資料助理紀錄',
                'db_table': 'insights_ask_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
