# Generated by Django 4.2.30 on 2026-04-27 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('student', '境外學生'), ('admin', '系統管理員')], default='student', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最後登入IP')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email 已驗證')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'users_customuser',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(choices=[('Indonesia', '印尼'), ('Malaysia', '馬來西亞'), ('Vietnam', '越南'), ('Thailand', '泰國'), ('Philippines', '菲律賓'), ('Cambodia', '柬埔寨'), ('Myanmar', '緬甸'), ('Japan', '日本'), ('Korea', '韓國'), ('Other', '其他')], max_length=50, verbose_name='國籍')),
                ('university', models.CharField(max_length=200, verbose_name='就讀學校')),
                ('identity_type', models.CharField(choices=[('overseas_chinese', '僑生（海外華裔）'), ('foreign_student', '外籍生（一般外國學生）'), ('exchange', '交換生'), ('preparatory', '僑大先修生')], max_length=30, verbose_name='身份別')),
                ('admission_status', models.CharField(choices=[('applied', '已提出申請'), ('admitted', '已收到錄取通知'), ('pre_arrival', '入境前準備中'), ('arrived', '已抵臺就學中')], default='applied', max_length=20, verbose_name='入學狀態')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='系所')),
                ('expected_arrival', models.DateField(blank=True, null=True, verbose_name='預計抵台日期')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='頭像')),
                ('preferred_language', models.CharField(default='zh-hant', max_length=10, verbose_name='慣用語言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號')),
            ],
            options={
                'verbose_name': '學生資料',
                'verbose_name_plural': '學生資料',
                'db_table': 'users_studentprofile',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_loginlog',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_emailverificationtoken',
            },
        ),
    ]
