# Generated by Django 5.2.13 on 2026-04-29 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='步驟名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('category', models.CharField(choices=[('pre_apply', '申請前準備'), ('pre_arrival', '抵台前辦理'), ('post_arrival', '抵台後辦理'), ('in_school', '在學期間')], max_length=20, verbose_name='階段')),
                ('identity_type', models.CharField(choices=[('all', '全部'), ('overseas_chinese', '僑生'), ('foreign_student', '外籍生'), ('exchange', '交換生'), ('preparatory', '僑大先修生')], default='all', max_length=20, verbose_name='適用身份')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('deadline_days', models.IntegerField(blank=True, null=True, verbose_name='建議完成天數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '流程步驟',
                'verbose_name_plural': '流程步驟',
                'db_table': 'flow_step',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='flow.flowstep', verbose_name='步驟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者進度',
                'verbose_name_plural': '使用者進度',
                'db_table': 'flow_userprogress',
                'unique_together': {('user', 'step')},
            },
        ),
    ]
